// Generated by scripts/generate-mochi-sprites.py.
// Source art: mochi-source-1.png and mochi-source-2.png.
import type { ImageSourcePropType } from 'react-native';

export type MoChiSpriteVariant = 'full' | 'face' | 'notice';

export type MoChiPoseKey =
  | 'idle'
  | 'angry'
  | 'sadCry'
  | 'celebrate'
  | 'confused'
  | 'calm'
  | 'foodPhone'
  | 'analyzing'
  | 'hydrate'
  | 'thumbsUp'
  | 'sparkleSuccess'
  | 'faceShocked'
  | 'faceSurprised'
  | 'faceSad'
  | 'faceTired'
  | 'faceThinking'
  | 'faceHappy'
  | 'faceEmbarrassed'
  | 'faceCalm'
  | 'faceLove'
  | 'faceDetermined'
  | 'islandAvatar'
  | 'faceCheerful'
  | 'faceStrained'
  | 'foodScale'
  | 'cakeConcern'
  | 'tabletLog'
  | 'tabletMeal'
  | 'carbExplain'
  | 'saladSuccess'
  | 'burgerSurprise'
  | 'mealChoice'
  | 'workout'
  | 'heartLove'
  | 'healthyBasket'
  | 'weighIn'
  | 'waterGlass'
  | 'reportReview'
  | 'reportPanic'
  | 'phoneMealPrep'
  | 'dietWarning'
  | 'cookingPrep'
  | 'spinChoice'
  | 'boxIdle'
  | 'scanThinkingFull'
  | 'scanSuccessFull'
  | 'scanErrorFull'
  | 'mealCoachFull'
  | 'waterCoachFull'
  | 'sleepyIdleFull'
  | 'secureAccountFull'
  | 'nutritionCoachNotice'
  | 'scanUncertainNotice'
  | 'listeningNotice'
  | 'weeklyReportNotice'
  | 'portionAdjustNotice'
  | 'mealPortionNotice'
  | 'logoutNotice'
  | 'scanSuccessFace'
  | 'scanUncertainFace'
  | 'softSorryFace'
  | 'secureFace';

export type MoChiSpriteMeta = {
  key: MoChiPoseKey;
  fileName: string;
  sourceSheet: 'mochi-source-1.png' | 'mochi-source-2.png' | 'hieukax970-2.png';
  includeComponents: number[];
  variant: MoChiSpriteVariant;
  labelVi: string;
  accessibilityLabel: string;
};

export const MOCHI_SPRITES: Record<MoChiPoseKey, ImageSourcePropType> = {
  idle: require('./sprites/01_idle.png'),
  angry: require('./sprites/02_angry.png'),
  sadCry: require('./sprites/03_sad_cry.png'),
  celebrate: require('./sprites/04_celebrate.png'),
  confused: require('./sprites/05_confused.png'),
  calm: require('./sprites/06_calm.png'),
  foodPhone: require('./sprites/07_food_phone.png'),
  analyzing: require('./sprites/08_analyzing.png'),
  hydrate: require('./sprites/09_hydrate.png'),
  thumbsUp: require('./sprites/10_thumbs_up.png'),
  sparkleSuccess: require('./sprites/11_sparkle_success.png'),
  faceShocked: require('./sprites/12_face_shocked.png'),
  faceSurprised: require('./sprites/13_face_surprised.png'),
  faceSad: require('./sprites/14_face_sad.png'),
  faceTired: require('./sprites/15_face_tired.png'),
  faceThinking: require('./sprites/16_face_thinking.png'),
  faceHappy: require('./sprites/17_face_happy.png'),
  faceEmbarrassed: require('./sprites/18_face_embarrassed.png'),
  faceCalm: require('./sprites/19_face_calm.png'),
  faceLove: require('./sprites/20_face_love.png'),
  faceDetermined: require('./sprites/21_face_determined.png'),
  islandAvatar: require('./sprites/44_island_avatar.png'),
  faceCheerful: require('./sprites/22_face_cheerful.png'),
  faceStrained: require('./sprites/23_face_strained.png'),
  foodScale: require('./sprites/24_food_scale.png'),
  cakeConcern: require('./sprites/25_cake_concern.png'),
  tabletLog: require('./sprites/26_tablet_log.png'),
  tabletMeal: require('./sprites/27_tablet_meal.png'),
  carbExplain: require('./sprites/28_carb_explain.png'),
  saladSuccess: require('./sprites/29_salad_success.png'),
  burgerSurprise: require('./sprites/30_burger_surprise.png'),
  mealChoice: require('./sprites/31_meal_choice.png'),
  workout: require('./sprites/32_workout.png'),
  heartLove: require('./sprites/33_heart_love.png'),
  healthyBasket: require('./sprites/34_healthy_basket.png'),
  weighIn: require('./sprites/35_weigh_in.png'),
  waterGlass: require('./sprites/36_water_glass.png'),
  reportReview: require('./sprites/37_report_review.png'),
  reportPanic: require('./sprites/38_report_panic.png'),
  phoneMealPrep: require('./sprites/39_phone_meal_prep.png'),
  dietWarning: require('./sprites/40_diet_warning.png'),
  cookingPrep: require('./sprites/41_cooking_prep.png'),
  spinChoice: require('./sprites/42_spin_choice.png'),
  boxIdle: require('./sprites/43_box_idle.png'),
  scanThinkingFull: require('./sprites/45_scan_thinking_full.png'),
  scanSuccessFull: require('./sprites/46_scan_success_full.png'),
  scanErrorFull: require('./sprites/47_scan_error_full.png'),
  mealCoachFull: require('./sprites/48_meal_coach_full.png'),
  waterCoachFull: require('./sprites/49_water_coach_full.png'),
  sleepyIdleFull: require('./sprites/50_sleepy_idle_full.png'),
  secureAccountFull: require('./sprites/51_secure_account_full.png'),
  nutritionCoachNotice: require('./sprites/52_nutrition_coach_notice.png'),
  scanUncertainNotice: require('./sprites/53_scan_uncertain_notice.png'),
  listeningNotice: require('./sprites/54_listening_notice.png'),
  weeklyReportNotice: require('./sprites/55_weekly_report_notice.png'),
  portionAdjustNotice: require('./sprites/56_portion_adjust_notice.png'),
  mealPortionNotice: require('./sprites/57_meal_portion_notice.png'),
  logoutNotice: require('./sprites/58_logout_notice.png'),
  scanSuccessFace: require('./sprites/59_scan_success_face.png'),
  scanUncertainFace: require('./sprites/60_scan_uncertain_face.png'),
  softSorryFace: require('./sprites/61_soft_sorry_face.png'),
  secureFace: require('./sprites/62_secure_face.png'),
};

export const MOCHI_SPRITE_METADATA: Record<MoChiPoseKey, MoChiSpriteMeta> = {
  idle: { key: 'idle', fileName: '01_idle.png', sourceSheet: 'mochi-source-1.png', includeComponents: [5], variant: 'full', labelVi: 'Đứng chờ', accessibilityLabel: 'MoChi đứng chờ' },
  angry: { key: 'angry', fileName: '02_angry.png', sourceSheet: 'mochi-source-1.png', includeComponents: [6], variant: 'full', labelVi: 'Căng thẳng', accessibilityLabel: 'MoChi căng thẳng' },
  sadCry: { key: 'sadCry', fileName: '03_sad_cry.png', sourceSheet: 'mochi-source-1.png', includeComponents: [7], variant: 'full', labelVi: 'Buồn', accessibilityLabel: 'MoChi buồn' },
  celebrate: { key: 'celebrate', fileName: '04_celebrate.png', sourceSheet: 'mochi-source-1.png', includeComponents: [1], variant: 'full', labelVi: 'Ăn mừng', accessibilityLabel: 'MoChi ăn mừng' },
  confused: { key: 'confused', fileName: '05_confused.png', sourceSheet: 'mochi-source-1.png', includeComponents: [3, 4, 8], variant: 'full', labelVi: 'Bối rối', accessibilityLabel: 'MoChi bối rối' },
  calm: { key: 'calm', fileName: '06_calm.png', sourceSheet: 'mochi-source-1.png', includeComponents: [2], variant: 'full', labelVi: 'Bình tĩnh', accessibilityLabel: 'MoChi bình tĩnh' },
  foodPhone: { key: 'foodPhone', fileName: '07_food_phone.png', sourceSheet: 'mochi-source-1.png', includeComponents: [9], variant: 'notice', labelVi: 'Nhắc ghi bữa', accessibilityLabel: 'MoChi nhắc ghi bữa' },
  analyzing: { key: 'analyzing', fileName: '08_analyzing.png', sourceSheet: 'mochi-source-1.png', includeComponents: [12, 14], variant: 'notice', labelVi: 'Đang phân tích', accessibilityLabel: 'MoChi đang phân tích' },
  hydrate: { key: 'hydrate', fileName: '09_hydrate.png', sourceSheet: 'mochi-source-1.png', includeComponents: [10, 11], variant: 'notice', labelVi: 'Nhắc uống nước', accessibilityLabel: 'MoChi nhắc uống nước' },
  thumbsUp: { key: 'thumbsUp', fileName: '10_thumbs_up.png', sourceSheet: 'mochi-source-1.png', includeComponents: [13], variant: 'notice', labelVi: 'Tốt lắm', accessibilityLabel: 'MoChi khen tốt lắm' },
  sparkleSuccess: { key: 'sparkleSuccess', fileName: '11_sparkle_success.png', sourceSheet: 'mochi-source-2.png', includeComponents: [1], variant: 'full', labelVi: 'Thành công rực rỡ', accessibilityLabel: 'MoChi ăn mừng thành công' },
  faceShocked: { key: 'faceShocked', fileName: '12_face_shocked.png', sourceSheet: 'mochi-source-1.png', includeComponents: [15], variant: 'face', labelVi: 'Hoảng hốt', accessibilityLabel: 'MoChi hoảng hốt' },
  faceSurprised: { key: 'faceSurprised', fileName: '13_face_surprised.png', sourceSheet: 'mochi-source-1.png', includeComponents: [16], variant: 'face', labelVi: 'Ngạc nhiên', accessibilityLabel: 'MoChi ngạc nhiên' },
  faceSad: { key: 'faceSad', fileName: '14_face_sad.png', sourceSheet: 'mochi-source-1.png', includeComponents: [19], variant: 'face', labelVi: 'Mặt buồn', accessibilityLabel: 'MoChi mặt buồn' },
  faceTired: { key: 'faceTired', fileName: '15_face_tired.png', sourceSheet: 'mochi-source-1.png', includeComponents: [20], variant: 'face', labelVi: 'Mệt mỏi', accessibilityLabel: 'MoChi mệt mỏi' },
  faceThinking: { key: 'faceThinking', fileName: '16_face_thinking.png', sourceSheet: 'mochi-source-1.png', includeComponents: [17], variant: 'face', labelVi: 'Suy nghĩ', accessibilityLabel: 'MoChi suy nghĩ' },
  faceHappy: { key: 'faceHappy', fileName: '17_face_happy.png', sourceSheet: 'mochi-source-1.png', includeComponents: [18], variant: 'face', labelVi: 'Vui vẻ', accessibilityLabel: 'MoChi vui vẻ' },
  faceEmbarrassed: { key: 'faceEmbarrassed', fileName: '18_face_embarrassed.png', sourceSheet: 'mochi-source-1.png', includeComponents: [21], variant: 'face', labelVi: 'Ngại ngùng', accessibilityLabel: 'MoChi ngại ngùng' },
  faceCalm: { key: 'faceCalm', fileName: '19_face_calm.png', sourceSheet: 'mochi-source-1.png', includeComponents: [22], variant: 'face', labelVi: 'Điềm tĩnh', accessibilityLabel: 'MoChi điềm tĩnh' },
  faceLove: { key: 'faceLove', fileName: '20_face_love.png', sourceSheet: 'mochi-source-1.png', includeComponents: [23], variant: 'face', labelVi: 'Yêu thích', accessibilityLabel: 'MoChi yêu thích' },
  faceDetermined: { key: 'faceDetermined', fileName: '21_face_determined.png', sourceSheet: 'mochi-source-1.png', includeComponents: [24], variant: 'face', labelVi: 'Quyết tâm', accessibilityLabel: 'MoChi quyết tâm' },
  islandAvatar: { key: 'islandAvatar', fileName: '44_island_avatar.png', sourceSheet: 'hieukax970-2.png', includeComponents: [23], variant: 'face', labelVi: 'Đại diện MoChi', accessibilityLabel: 'MoChi đang theo dõi ngữ cảnh' },
  faceCheerful: { key: 'faceCheerful', fileName: '22_face_cheerful.png', sourceSheet: 'mochi-source-1.png', includeComponents: [25], variant: 'face', labelVi: 'Tươi tỉnh', accessibilityLabel: 'MoChi tươi tỉnh' },
  faceStrained: { key: 'faceStrained', fileName: '23_face_strained.png', sourceSheet: 'mochi-source-1.png', includeComponents: [26], variant: 'face', labelVi: 'Khó chịu', accessibilityLabel: 'MoChi khó chịu' },
  foodScale: { key: 'foodScale', fileName: '24_food_scale.png', sourceSheet: 'mochi-source-2.png', includeComponents: [4], variant: 'full', labelVi: 'Cân món ăn', accessibilityLabel: 'MoChi cân món ăn' },
  cakeConcern: { key: 'cakeConcern', fileName: '25_cake_concern.png', sourceSheet: 'mochi-source-2.png', includeComponents: [6, 7], variant: 'full', labelVi: 'Cân nhắc món ngọt', accessibilityLabel: 'MoChi cân nhắc món ngọt' },
  tabletLog: { key: 'tabletLog', fileName: '26_tablet_log.png', sourceSheet: 'mochi-source-2.png', includeComponents: [2], variant: 'full', labelVi: 'Ghi trên tablet', accessibilityLabel: 'MoChi ghi trên tablet' },
  tabletMeal: { key: 'tabletMeal', fileName: '27_tablet_meal.png', sourceSheet: 'mochi-source-2.png', includeComponents: [5], variant: 'full', labelVi: 'Ghi bữa ăn', accessibilityLabel: 'MoChi ghi bữa ăn' },
  carbExplain: { key: 'carbExplain', fileName: '28_carb_explain.png', sourceSheet: 'mochi-source-2.png', includeComponents: [3, 8], variant: 'notice', labelVi: 'Giải thích dinh dưỡng', accessibilityLabel: 'MoChi giải thích dinh dưỡng' },
  saladSuccess: { key: 'saladSuccess', fileName: '29_salad_success.png', sourceSheet: 'mochi-source-2.png', includeComponents: [10], variant: 'notice', labelVi: 'Ghi bữa thành công', accessibilityLabel: 'MoChi ghi bữa thành công' },
  burgerSurprise: { key: 'burgerSurprise', fileName: '30_burger_surprise.png', sourceSheet: 'mochi-source-2.png', includeComponents: [11], variant: 'notice', labelVi: 'Ngạc nhiên với món ăn', accessibilityLabel: 'MoChi ngạc nhiên với món ăn' },
  mealChoice: { key: 'mealChoice', fileName: '31_meal_choice.png', sourceSheet: 'mochi-source-2.png', includeComponents: [12, 16], variant: 'notice', labelVi: 'Chọn món', accessibilityLabel: 'MoChi chọn món' },
  workout: { key: 'workout', fileName: '32_workout.png', sourceSheet: 'mochi-source-2.png', includeComponents: [13], variant: 'full', labelVi: 'Tập luyện', accessibilityLabel: 'MoChi tập luyện' },
  heartLove: { key: 'heartLove', fileName: '33_heart_love.png', sourceSheet: 'mochi-source-2.png', includeComponents: [9, 14], variant: 'notice', labelVi: 'Yêu thích', accessibilityLabel: 'MoChi yêu thích' },
  healthyBasket: { key: 'healthyBasket', fileName: '34_healthy_basket.png', sourceSheet: 'mochi-source-2.png', includeComponents: [15], variant: 'notice', labelVi: 'Giỏ món lành mạnh', accessibilityLabel: 'MoChi cầm giỏ món lành mạnh' },
  weighIn: { key: 'weighIn', fileName: '35_weigh_in.png', sourceSheet: 'mochi-source-2.png', includeComponents: [18], variant: 'full', labelVi: 'Cân nặng', accessibilityLabel: 'MoChi cân nặng' },
  waterGlass: { key: 'waterGlass', fileName: '36_water_glass.png', sourceSheet: 'mochi-source-2.png', includeComponents: [21, 22], variant: 'notice', labelVi: 'Ly nước', accessibilityLabel: 'MoChi cầm ly nước' },
  reportReview: { key: 'reportReview', fileName: '37_report_review.png', sourceSheet: 'mochi-source-2.png', includeComponents: [19], variant: 'notice', labelVi: 'Xem báo cáo', accessibilityLabel: 'MoChi xem báo cáo' },
  reportPanic: { key: 'reportPanic', fileName: '38_report_panic.png', sourceSheet: 'mochi-source-2.png', includeComponents: [17, 16], variant: 'notice', labelVi: 'Báo cáo căng', accessibilityLabel: 'MoChi căng thẳng với báo cáo' },
  phoneMealPrep: { key: 'phoneMealPrep', fileName: '39_phone_meal_prep.png', sourceSheet: 'mochi-source-2.png', includeComponents: [26, 30], variant: 'notice', labelVi: 'Chuẩn bị bữa', accessibilityLabel: 'MoChi chuẩn bị bữa' },
  dietWarning: { key: 'dietWarning', fileName: '40_diet_warning.png', sourceSheet: 'mochi-source-2.png', includeComponents: [29], variant: 'notice', labelVi: 'Cảnh báo ăn kiêng', accessibilityLabel: 'MoChi cảnh báo ăn kiêng' },
  cookingPrep: { key: 'cookingPrep', fileName: '41_cooking_prep.png', sourceSheet: 'mochi-source-2.png', includeComponents: [27], variant: 'notice', labelVi: 'Chuẩn bị nấu', accessibilityLabel: 'MoChi chuẩn bị nấu' },
  spinChoice: { key: 'spinChoice', fileName: '42_spin_choice.png', sourceSheet: 'mochi-source-2.png', includeComponents: [28], variant: 'full', labelVi: 'Vòng chọn món', accessibilityLabel: 'MoChi quay vòng chọn món' },
  boxIdle: { key: 'boxIdle', fileName: '43_box_idle.png', sourceSheet: 'mochi-source-2.png', includeComponents: [24], variant: 'full', labelVi: 'Đứng trên bục', accessibilityLabel: 'MoChi đứng trên bục' },
  scanThinkingFull: { key: 'scanThinkingFull', fileName: '45_scan_thinking_full.png', sourceSheet: 'hieukax970-2.png', includeComponents: [1], variant: 'full', labelVi: 'Soi món ăn', accessibilityLabel: 'MoChi đang soi món ăn' },
  scanSuccessFull: { key: 'scanSuccessFull', fileName: '46_scan_success_full.png', sourceSheet: 'hieukax970-2.png', includeComponents: [2], variant: 'full', labelVi: 'Scan thành công', accessibilityLabel: 'MoChi báo scan thành công' },
  scanErrorFull: { key: 'scanErrorFull', fileName: '47_scan_error_full.png', sourceSheet: 'hieukax970-2.png', includeComponents: [3], variant: 'full', labelVi: 'Scan cần thử lại', accessibilityLabel: 'MoChi báo scan cần thử lại' },
  mealCoachFull: { key: 'mealCoachFull', fileName: '48_meal_coach_full.png', sourceSheet: 'hieukax970-2.png', includeComponents: [4], variant: 'full', labelVi: 'Nhắc bữa ăn', accessibilityLabel: 'MoChi nhắc ghi bữa ăn' },
  waterCoachFull: { key: 'waterCoachFull', fileName: '49_water_coach_full.png', sourceSheet: 'hieukax970-2.png', includeComponents: [5], variant: 'full', labelVi: 'Nhắc uống nước', accessibilityLabel: 'MoChi nhắc uống nước' },
  sleepyIdleFull: { key: 'sleepyIdleFull', fileName: '50_sleepy_idle_full.png', sourceSheet: 'hieukax970-2.png', includeComponents: [7], variant: 'full', labelVi: 'Nghỉ một nhịp', accessibilityLabel: 'MoChi nhắc nghỉ một nhịp' },
  secureAccountFull: { key: 'secureAccountFull', fileName: '51_secure_account_full.png', sourceSheet: 'hieukax970-2.png', includeComponents: [8], variant: 'full', labelVi: 'Bảo mật tài khoản', accessibilityLabel: 'MoChi nhắc bảo mật tài khoản' },
  nutritionCoachNotice: { key: 'nutritionCoachNotice', fileName: '52_nutrition_coach_notice.png', sourceSheet: 'hieukax970-2.png', includeComponents: [9], variant: 'notice', labelVi: 'Kiểm tra dinh dưỡng', accessibilityLabel: 'MoChi kiểm tra dinh dưỡng' },
  scanUncertainNotice: { key: 'scanUncertainNotice', fileName: '53_scan_uncertain_notice.png', sourceSheet: 'hieukax970-2.png', includeComponents: [10], variant: 'notice', labelVi: 'Kết quả cần kiểm tra', accessibilityLabel: 'MoChi báo kết quả cần kiểm tra' },
  listeningNotice: { key: 'listeningNotice', fileName: '54_listening_notice.png', sourceSheet: 'hieukax970-2.png', includeComponents: [11], variant: 'notice', labelVi: 'Đang nghe', accessibilityLabel: 'MoChi đang nghe' },
  weeklyReportNotice: { key: 'weeklyReportNotice', fileName: '55_weekly_report_notice.png', sourceSheet: 'hieukax970-2.png', includeComponents: [13], variant: 'notice', labelVi: 'Xem báo cáo', accessibilityLabel: 'MoChi xem báo cáo' },
  portionAdjustNotice: { key: 'portionAdjustNotice', fileName: '56_portion_adjust_notice.png', sourceSheet: 'hieukax970-2.png', includeComponents: [14], variant: 'notice', labelVi: 'Chỉnh khẩu phần', accessibilityLabel: 'MoChi nhắc chỉnh khẩu phần' },
  mealPortionNotice: { key: 'mealPortionNotice', fileName: '57_meal_portion_notice.png', sourceSheet: 'hieukax970-2.png', includeComponents: [15], variant: 'notice', labelVi: 'Kiểm tra khẩu phần', accessibilityLabel: 'MoChi kiểm tra khẩu phần bữa ăn' },
  logoutNotice: { key: 'logoutNotice', fileName: '58_logout_notice.png', sourceSheet: 'hieukax970-2.png', includeComponents: [16], variant: 'notice', labelVi: 'Tài khoản', accessibilityLabel: 'MoChi hỗ trợ thao tác tài khoản' },
  scanSuccessFace: { key: 'scanSuccessFace', fileName: '59_scan_success_face.png', sourceSheet: 'hieukax970-2.png', includeComponents: [17], variant: 'face', labelVi: 'Scan ổn rồi', accessibilityLabel: 'MoChi vui vì scan thành công' },
  scanUncertainFace: { key: 'scanUncertainFace', fileName: '60_scan_uncertain_face.png', sourceSheet: 'hieukax970-2.png', includeComponents: [18], variant: 'face', labelVi: 'Scan chưa chắc', accessibilityLabel: 'MoChi chưa chắc về kết quả scan' },
  softSorryFace: { key: 'softSorryFace', fileName: '61_soft_sorry_face.png', sourceSheet: 'hieukax970-2.png', includeComponents: [19], variant: 'face', labelVi: 'Xin lỗi nhẹ', accessibilityLabel: 'MoChi xin lỗi nhẹ nhàng' },
  secureFace: { key: 'secureFace', fileName: '62_secure_face.png', sourceSheet: 'hieukax970-2.png', includeComponents: [21], variant: 'face', labelVi: 'Cẩn trọng', accessibilityLabel: 'MoChi nhắc cẩn trọng' },
};
