// <auto-generated />
using System;
using EatFitAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EatFitAI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251027031407_InitialCustomSchema")]
    partial class InitialCustomSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EatFitAI.Domain.Ai.AiRecipe", b =>
                {
                    b.Property<long>("MaGoiYAI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaGoiYAI");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaGoiYAI"));

                    b.Property<string>("DuLieuDauVao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DuLieuDauVao");

                    b.Property<string>("KetQuaAI")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KetQuaAI");

                    b.Property<string>("LoaiDeXuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LoaiDeXuat");

                    b.Property<Guid?>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaNguoiDung");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ThoiGianTao");

                    b.Property<int?>("ThoiLuongXuLyMs")
                        .HasColumnType("int")
                        .HasColumnName("ThoiLuongXuLyMs");

                    b.HasKey("MaGoiYAI");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("NhatKyAI", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Ai.ImageRecognition", b =>
                {
                    b.Property<long>("MaNhanDien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaNhanDien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaNhanDien"));

                    b.Property<decimal?>("DoTinCay")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("DoTinCay");

                    b.Property<long>("MaGoiYAI")
                        .HasColumnType("bigint")
                        .HasColumnName("MaGoiYAI");

                    b.Property<string>("Nhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nhan");

                    b.HasKey("MaNhanDien");

                    b.HasIndex("MaGoiYAI");

                    b.ToTable("NhanDienAnh", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("MaRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaRefreshToken");

                    b.Property<DateTime>("HetHanVao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HetHanVao");

                    b.Property<string>("LyDoThuHoi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LyDoThuHoi");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaNguoiDung");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("TaoBoiIP")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TaoBoiIP");

                    b.Property<string>("ThayTheBangToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ThayTheBangToken");

                    b.Property<string>("ThuHoiBoiIP")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ThuHoiBoiIP");

                    b.Property<DateTime?>("ThuHoiVao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ThuHoiVao");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Token");

                    b.HasKey("MaRefreshToken");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Diary.DiaryEntry", b =>
                {
                    b.Property<long>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaNhatKy");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaNhatKy"));

                    b.Property<decimal>("Calo")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Calo");

                    b.Property<decimal>("Carb")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Carb");

                    b.Property<decimal>("Fat")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Fat");

                    b.Property<decimal>("KhoiLuongGram")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("KhoiLuongGram");

                    b.Property<string>("MaBuaAn")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("MaBuaAn");

                    b.Property<long?>("MaCongThuc")
                        .HasColumnType("bigint")
                        .HasColumnName("MaCongThuc");

                    b.Property<long?>("MaMonNguoiDung")
                        .HasColumnType("bigint")
                        .HasColumnName("MaMonNguoiDung");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaNguoiDung");

                    b.Property<long?>("MaThucPham")
                        .HasColumnType("bigint")
                        .HasColumnName("MaThucPham");

                    b.Property<string>("MealTypeMaBuaAn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayAn")
                        .HasColumnType("date")
                        .HasColumnName("NgayAn");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("Protein")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Protein");

                    b.HasKey("MaNhatKy");

                    b.HasIndex("MaBuaAn");

                    b.HasIndex("MaCongThuc");

                    b.HasIndex("MaMonNguoiDung");

                    b.HasIndex("MaThucPham");

                    b.HasIndex("MealTypeMaBuaAn");

                    b.HasIndex("MaNguoiDung", "NgayAn", "MaBuaAn", "MaThucPham", "MaMonNguoiDung", "MaCongThuc")
                        .IsUnique()
                        .HasFilter("[MaThucPham] IS NOT NULL AND [MaMonNguoiDung] IS NOT NULL AND [MaCongThuc] IS NOT NULL");

                    b.ToTable("NhatKyAnUong", null, t =>
                        {
                            t.HasCheckConstraint("CK_NK_ChiMotNguon", "(CASE WHEN [MaThucPham] IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN [MaMonNguoiDung] IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN [MaCongThuc] IS NOT NULL THEN 1 ELSE 0 END) = 1");
                        });
                });

            modelBuilder.Entity("EatFitAI.Domain.Diary.MealType", b =>
                {
                    b.Property<string>("MaBuaAn")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MaBuaAn");

                    b.Property<string>("TenBuaAn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenBuaAn");

                    b.HasKey("MaBuaAn");

                    b.ToTable("LoaiBuaAn", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Foods.CustomDish", b =>
                {
                    b.Property<long>("MaMonNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaMonNguoiDung");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaMonNguoiDung"));

                    b.Property<decimal>("Calo100g")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Calo100g");

                    b.Property<decimal>("Carb100g")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Carb100g");

                    b.Property<decimal>("Fat100g")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Fat100g");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaNguoiDung");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("Protein100g")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Protein100g");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenMon");

                    b.HasKey("MaMonNguoiDung");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("MonNguoiDung", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Foods.CustomDishIngredient", b =>
                {
                    b.Property<long>("MaNguyenLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaNguyenLieu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaNguyenLieu"));

                    b.Property<decimal>("CaloKcal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("CaloKcal");

                    b.Property<decimal>("CarbG")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("CarbG");

                    b.Property<decimal>("FatG")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("FatG");

                    b.Property<decimal>("KhoiLuongGram")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("KhoiLuongGram");

                    b.Property<long>("MaMonNguoiDung")
                        .HasColumnType("bigint")
                        .HasColumnName("MaMonNguoiDung");

                    b.Property<long>("MaThucPham")
                        .HasColumnType("bigint")
                        .HasColumnName("MaThucPham");

                    b.Property<decimal>("ProteinG")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("ProteinG");

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenNguyenLieu");

                    b.HasKey("MaNguyenLieu");

                    b.HasIndex("MaMonNguoiDung");

                    b.HasIndex("MaThucPham");

                    b.ToTable("NguyenLieuMonNguoiDung", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Foods.Food", b =>
                {
                    b.Property<long>("MaThucPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaThucPham");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaThucPham"));

                    b.Property<decimal>("Calo100g")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Calo100g");

                    b.Property<decimal>("Carb100g")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Carb100g");

                    b.Property<decimal>("Fat100g")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Fat100g");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HinhAnh");

                    b.Property<string>("MoTaKhauPhan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTaKhauPhan");

                    b.Property<string>("NhomThucPham")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NhomThucPham");

                    b.Property<decimal>("Protein100g")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Protein100g");

                    b.Property<string>("TenThucPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TenThucPham");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaThucPham");

                    b.HasIndex("TenThucPham");

                    b.ToTable("ThucPham", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Foods.Recipe", b =>
                {
                    b.Property<long>("MaCongThuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaCongThuc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaCongThuc"));

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HinhAnh");

                    b.Property<string>("HuongDanCheBien")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HuongDanCheBien");

                    b.Property<string>("LoaiMon")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LoaiMon");

                    b.Property<string>("TenCongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenCongThuc");

                    b.Property<int?>("ThoiGianUocTinhPhut")
                        .HasColumnType("int")
                        .HasColumnName("ThoiGianUocTinhPhut");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaCongThuc");

                    b.ToTable("CongThuc", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Foods.RecipeIngredient", b =>
                {
                    b.Property<long>("MaNguyenLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaNguyenLieu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaNguyenLieu"));

                    b.Property<decimal>("KhoiLuongGram")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("KhoiLuongGram");

                    b.Property<long>("MaCongThuc")
                        .HasColumnType("bigint")
                        .HasColumnName("MaCongThuc");

                    b.Property<long>("MaThucPham")
                        .HasColumnType("bigint")
                        .HasColumnName("MaThucPham");

                    b.Property<long?>("RecipeMaCongThuc")
                        .HasColumnType("bigint");

                    b.HasKey("MaNguyenLieu");

                    b.HasIndex("MaThucPham");

                    b.HasIndex("RecipeMaCongThuc");

                    b.ToTable("NguyenLieuCongThuc", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Metadata.ScriptHistory", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaLichSu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("TenFile");

                    b.Property<DateTime>("ThoiGianApDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ThoiGianApDung")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("MaLichSu");

                    b.HasIndex("TenFile")
                        .IsUnique();

                    b.ToTable("LichSuCapNhat", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Nutrition.ActivityLevel", b =>
                {
                    b.Property<string>("MaMucDo")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MaMucDo");

                    b.Property<decimal>("HeSoTDEE")
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("HeSoTDEE");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<string>("TenMucDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenMucDo");

                    b.HasKey("MaMucDo");

                    b.ToTable("MucDoVanDong", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Nutrition.BodyMetric", b =>
                {
                    b.Property<long>("MaChiSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaChiSo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaChiSo"));

                    b.Property<string>("ActivityLevelMaMucDo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("CanNangKg")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("CanNangKg");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<string>("GoalMaMucTieu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("KhoiLuongCoKg")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("KhoiLuongCoKg");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaNguoiDung");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<decimal?>("PhanTramMoCoThe")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PhanTramMoCoThe");

                    b.Property<decimal?>("VongEoCm")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("VongEoCm");

                    b.Property<decimal?>("VongMongCm")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("VongMongCm");

                    b.HasKey("MaChiSo");

                    b.HasIndex("ActivityLevelMaMucDo");

                    b.HasIndex("GoalMaMucTieu");

                    b.HasIndex("MaNguoiDung", "NgayCapNhat");

                    b.ToTable("ChiSoCoThe", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Nutrition.Goal", b =>
                {
                    b.Property<string>("MaMucTieu")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MaMucTieu");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<string>("TenMucTieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenMucTieu");

                    b.HasKey("MaMucTieu");

                    b.ToTable("MucTieu", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Nutrition.NutritionTarget", b =>
                {
                    b.Property<long>("MaMucTieuDD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaMucTieuDD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaMucTieuDD"));

                    b.Property<int>("CaloKcal")
                        .HasColumnType("int")
                        .HasColumnName("CaloKcal");

                    b.Property<decimal>("CarbG")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("CarbG");

                    b.Property<decimal>("FatG")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("FatG");

                    b.Property<DateTime>("HieuLucTuNgay")
                        .HasColumnType("date")
                        .HasColumnName("HieuLucTuNgay");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LyDo");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaNguoiDung");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nguon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nguon");

                    b.Property<decimal>("ProteinG")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("ProteinG");

                    b.HasKey("MaMucTieuDD");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("MucTieuDinhDuong", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Users.NguoiDung", b =>
                {
                    b.Property<Guid>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaNguoiDung");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Email");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GioiTinh");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HoTen");

                    b.Property<byte[]>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("MatKhauHash");

                    b.Property<DateTime>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("NgaySinh");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Users.UserProfile", b =>
                {
                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaNguoiDung");

                    b.Property<string>("AnhDaiDienUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AnhDaiDienUrl");

                    b.Property<decimal?>("CanNangMucTieuKg")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("CanNangMucTieuKg");

                    b.Property<decimal?>("ChieuCaoCm")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("ChieuCaoCm");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GioiTinh");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HoTen");

                    b.Property<string>("MucDoVanDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MucDoVanDong");

                    b.Property<string>("MucTieu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MucTieu");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("NgaySinh");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("HoSoNguoiDung", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Ai.AiRecipe", b =>
                {
                    b.HasOne("EatFitAI.Domain.Users.NguoiDung", "User")
                        .WithMany("AiRecipes")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.Domain.Ai.ImageRecognition", b =>
                {
                    b.HasOne("EatFitAI.Domain.Ai.AiRecipe", "AiRecipe")
                        .WithMany("ImageRecognitions")
                        .HasForeignKey("MaGoiYAI")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiRecipe");
                });

            modelBuilder.Entity("EatFitAI.Domain.Auth.RefreshToken", b =>
                {
                    b.HasOne("EatFitAI.Domain.Users.NguoiDung", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.Domain.Diary.DiaryEntry", b =>
                {
                    b.HasOne("EatFitAI.Domain.Diary.MealType", null)
                        .WithMany("DiaryEntries")
                        .HasForeignKey("MaBuaAn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EatFitAI.Domain.Foods.Recipe", "Recipe")
                        .WithMany("DiaryEntries")
                        .HasForeignKey("MaCongThuc")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EatFitAI.Domain.Foods.CustomDish", "CustomDish")
                        .WithMany("DiaryEntries")
                        .HasForeignKey("MaMonNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EatFitAI.Domain.Users.NguoiDung", "User")
                        .WithMany("DiaryEntries")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatFitAI.Domain.Foods.Food", "Food")
                        .WithMany("DiaryEntries")
                        .HasForeignKey("MaThucPham")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EatFitAI.Domain.Diary.MealType", "MealType")
                        .WithMany()
                        .HasForeignKey("MealTypeMaBuaAn");

                    b.Navigation("CustomDish");

                    b.Navigation("Food");

                    b.Navigation("MealType");

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.Domain.Foods.CustomDish", b =>
                {
                    b.HasOne("EatFitAI.Domain.Users.NguoiDung", "User")
                        .WithMany("CustomDishes")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.Domain.Foods.CustomDishIngredient", b =>
                {
                    b.HasOne("EatFitAI.Domain.Foods.CustomDish", "CustomDish")
                        .WithMany("Ingredients")
                        .HasForeignKey("MaMonNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatFitAI.Domain.Foods.Food", "Food")
                        .WithMany("CustomDishIngredients")
                        .HasForeignKey("MaThucPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomDish");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("EatFitAI.Domain.Foods.RecipeIngredient", b =>
                {
                    b.HasOne("EatFitAI.Domain.Foods.Food", "Food")
                        .WithMany()
                        .HasForeignKey("MaThucPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EatFitAI.Domain.Foods.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeMaCongThuc");

                    b.Navigation("Food");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("EatFitAI.Domain.Nutrition.BodyMetric", b =>
                {
                    b.HasOne("EatFitAI.Domain.Nutrition.ActivityLevel", null)
                        .WithMany("BodyMetrics")
                        .HasForeignKey("ActivityLevelMaMucDo");

                    b.HasOne("EatFitAI.Domain.Nutrition.Goal", null)
                        .WithMany("BodyMetrics")
                        .HasForeignKey("GoalMaMucTieu");

                    b.HasOne("EatFitAI.Domain.Users.NguoiDung", "User")
                        .WithMany("BodyMetrics")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.Domain.Nutrition.NutritionTarget", b =>
                {
                    b.HasOne("EatFitAI.Domain.Users.NguoiDung", "User")
                        .WithMany("NutritionTargets")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.Domain.Users.UserProfile", b =>
                {
                    b.HasOne("EatFitAI.Domain.Users.NguoiDung", "User")
                        .WithOne("Profile")
                        .HasForeignKey("EatFitAI.Domain.Users.UserProfile", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.Domain.Ai.AiRecipe", b =>
                {
                    b.Navigation("ImageRecognitions");
                });

            modelBuilder.Entity("EatFitAI.Domain.Diary.MealType", b =>
                {
                    b.Navigation("DiaryEntries");
                });

            modelBuilder.Entity("EatFitAI.Domain.Foods.CustomDish", b =>
                {
                    b.Navigation("DiaryEntries");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("EatFitAI.Domain.Foods.Food", b =>
                {
                    b.Navigation("CustomDishIngredients");

                    b.Navigation("DiaryEntries");
                });

            modelBuilder.Entity("EatFitAI.Domain.Foods.Recipe", b =>
                {
                    b.Navigation("DiaryEntries");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("EatFitAI.Domain.Nutrition.ActivityLevel", b =>
                {
                    b.Navigation("BodyMetrics");
                });

            modelBuilder.Entity("EatFitAI.Domain.Nutrition.Goal", b =>
                {
                    b.Navigation("BodyMetrics");
                });

            modelBuilder.Entity("EatFitAI.Domain.Users.NguoiDung", b =>
                {
                    b.Navigation("AiRecipes");

                    b.Navigation("BodyMetrics");

                    b.Navigation("CustomDishes");

                    b.Navigation("DiaryEntries");

                    b.Navigation("NutritionTargets");

                    b.Navigation("Profile");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
