// <auto-generated />
using System;
using EatFitAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EatFitAI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EatFitAI.Domain.Ai.AiRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CaloriesKcal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CarbohydrateGrams")
                        .HasColumnType("decimal(9,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("FatGrams")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("IngredientsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProteinGrams")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("StepsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AiRecipe", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaRefreshToken");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TaoBoiIP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("HetHanVao");

                    b.Property<string>("ReasonRevoked")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LyDoThuHoi");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ThayTheBangToken");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ThuHoiVao");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ThuHoiBoiIP");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Diary.DiaryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaNhatKy");

                    b.Property<Guid?>("AiRecipeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaCongThucAI");

                    b.Property<decimal>("CaloriesKcal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Calo");

                    b.Property<decimal>("CarbohydrateGrams")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Carb");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CustomDishId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaMonNguoiDung");

                    b.Property<decimal>("FatGrams")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Fat");

                    b.Property<Guid?>("FoodId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaThucPham");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaMuc");

                    b.Property<string>("MealCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("MaBuaAn");

                    b.Property<DateTime>("MealDate")
                        .HasColumnType("date")
                        .HasColumnName("NgayAn");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<decimal>("ProteinGrams")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Protein");

                    b.Property<decimal>("QuantityGrams")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("KhoiLuongGram");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("Nguon");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("AiRecipeId");

                    b.HasIndex("CustomDishId");

                    b.HasIndex("FoodId");

                    b.HasIndex("UserId", "MealDate", "MealCode", "ItemId", "Source")
                        .IsUnique();

                    b.ToTable("NhatKyAnUong", null, t =>
                        {
                            t.HasCheckConstraint("CK_NK_ChiMotNguon", "(CASE WHEN [MaThucPham] IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN [MaMonNguoiDung] IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN [MaCongThucAI] IS NOT NULL THEN 1 ELSE 0 END) = 1");
                        });
                });

            modelBuilder.Entity("EatFitAI.Domain.Foods.CustomDish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaMonNguoiDung");

                    b.Property<decimal>("CaloriesKcal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Calo100g");

                    b.Property<decimal>("CarbohydrateGrams")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Carb100g");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<decimal>("FatGrams")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Fat100g");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenMon");

                    b.Property<decimal>("PortionSizeGrams")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("KhoiLuongPhucVuGram");

                    b.Property<decimal>("ProteinGrams")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Protein100g");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MonNguoiDung", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Foods.CustomDishIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CaloriesKcal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CarbohydrateGrams")
                        .HasColumnType("decimal(9,2)");

                    b.Property<Guid>("CustomDishId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FatGrams")
                        .HasColumnType("decimal(9,2)");

                    b.Property<Guid?>("FoodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProteinGrams")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("QuantityGrams")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomDishId");

                    b.HasIndex("FoodId");

                    b.ToTable("CustomDishIngredient", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Foods.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaThucPham");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ThuongHieu");

                    b.Property<decimal>("CaloriesKcal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Calo100g");

                    b.Property<decimal>("CarbohydrateGrams")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Carb100g");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PhanLoai");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTaKhauPhan");

                    b.Property<decimal>("FatGrams")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Fat100g");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("bit")
                        .HasColumnName("LaTuDinhNghia");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TenThucPham");

                    b.Property<decimal>("ProteinGrams")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Protein100g");

                    b.Property<decimal>("ServingSizeGrams")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("KhoiLuongPhucVuGram");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("ThucPham", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Metadata.ScriptHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.HasKey("Id");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.ToTable("ScriptHistory", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Nutrition.BodyMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaChiSo");

                    b.Property<decimal?>("BodyFatPercent")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("TiLeMoCoThe");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal?>("HipCm")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("VongMongCm");

                    b.Property<decimal?>("MuscleMassKg")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("KhoiLuongCoKg");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaNguoiDung");

                    b.Property<decimal?>("WaistCm")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("VongEoCm");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("CanNangKg");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RecordedAt");

                    b.ToTable("ChiSoCoThe", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Nutrition.NutritionTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaMucTieuDD");

                    b.Property<decimal>("CaloriesKcal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("CaloKcal");

                    b.Property<decimal>("CarbohydrateGrams")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("CarbG");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("HieuLucTuNgay");

                    b.Property<decimal>("FatGrams")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("FatG");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("LaHoatDong");

                    b.Property<decimal>("ProteinGrams")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("ProteinG");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("MucTieuDinhDuong", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Users.NguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaNguoiDung");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("SoLanDangNhapThatBai");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DauDongBo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("NgaySinh");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("EmailXacNhan");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HoTen");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GioiTinh");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("KichHoatKhoa");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("KetThucKhoa");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("EmailChuanHoa");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("TenDangNhapChuanHoa");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MatKhauHash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SoDienThoai");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("SoDienThoaiXacNhan");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DauAnToan");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("KichHoatHaiYeuTo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("TenDangNhap");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex")
                        .HasFilter("[EmailChuanHoa] IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[TenDangNhapChuanHoa] IS NOT NULL");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Users.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaNguoiDung");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MucDoHoatDong");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AnhDaiDienUrl");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("NgaySinh");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HoTen");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GioiTinh");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MucTieu");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("ChieuCaoCm");

                    b.Property<decimal?>("TargetWeightKg")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("CanNangMucTieuKg");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.HasKey("UserId");

                    b.ToTable("HoSoNguoiDung", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaVaiTro");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaClaim");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("VaiTroClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaClaim");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NguoiDungClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("NguoiDungLogin", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaNguoiDung");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("NguoiDungVaiTro", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("NguoiDungToken", (string)null);
                });

            modelBuilder.Entity("EatFitAI.Domain.Ai.AiRecipe", b =>
                {
                    b.HasOne("EatFitAI.Domain.Users.NguoiDung", "User")
                        .WithMany("AiRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.Domain.Auth.RefreshToken", b =>
                {
                    b.HasOne("EatFitAI.Domain.Users.NguoiDung", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.Domain.Diary.DiaryEntry", b =>
                {
                    b.HasOne("EatFitAI.Domain.Ai.AiRecipe", "AiRecipe")
                        .WithMany("DiaryEntries")
                        .HasForeignKey("AiRecipeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EatFitAI.Domain.Foods.CustomDish", "CustomDish")
                        .WithMany("DiaryEntries")
                        .HasForeignKey("CustomDishId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EatFitAI.Domain.Foods.Food", "Food")
                        .WithMany("DiaryEntries")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EatFitAI.Domain.Users.NguoiDung", "User")
                        .WithMany("DiaryEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiRecipe");

                    b.Navigation("CustomDish");

                    b.Navigation("Food");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.Domain.Foods.CustomDish", b =>
                {
                    b.HasOne("EatFitAI.Domain.Users.NguoiDung", "User")
                        .WithMany("CustomDishes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.Domain.Foods.CustomDishIngredient", b =>
                {
                    b.HasOne("EatFitAI.Domain.Foods.CustomDish", "CustomDish")
                        .WithMany("Ingredients")
                        .HasForeignKey("CustomDishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatFitAI.Domain.Foods.Food", "Food")
                        .WithMany("CustomDishIngredients")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CustomDish");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("EatFitAI.Domain.Nutrition.BodyMetric", b =>
                {
                    b.HasOne("EatFitAI.Domain.Users.NguoiDung", "User")
                        .WithMany("BodyMetrics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.Domain.Nutrition.NutritionTarget", b =>
                {
                    b.HasOne("EatFitAI.Domain.Users.NguoiDung", "User")
                        .WithMany("NutritionTargets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.Domain.Users.UserProfile", b =>
                {
                    b.HasOne("EatFitAI.Domain.Users.NguoiDung", "User")
                        .WithOne("Profile")
                        .HasForeignKey("EatFitAI.Domain.Users.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("EatFitAI.Domain.Users.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("EatFitAI.Domain.Users.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatFitAI.Domain.Users.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("EatFitAI.Domain.Users.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EatFitAI.Domain.Ai.AiRecipe", b =>
                {
                    b.Navigation("DiaryEntries");
                });

            modelBuilder.Entity("EatFitAI.Domain.Foods.CustomDish", b =>
                {
                    b.Navigation("DiaryEntries");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("EatFitAI.Domain.Foods.Food", b =>
                {
                    b.Navigation("CustomDishIngredients");

                    b.Navigation("DiaryEntries");
                });

            modelBuilder.Entity("EatFitAI.Domain.Users.NguoiDung", b =>
                {
                    b.Navigation("AiRecipes");

                    b.Navigation("BodyMetrics");

                    b.Navigation("CustomDishes");

                    b.Navigation("DiaryEntries");

                    b.Navigation("NutritionTargets");

                    b.Navigation("Profile");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
