/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analytics/nutrition-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    startDate?: string;
                    endDate?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NutritionSummaryDto"];
                        "application/json": components["schemas"]["NutritionSummaryDto"];
                        "text/json": components["schemas"]["NutritionSummaryDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                    "text/json": components["schemas"]["RegisterRequest"];
                    "application/*+json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponse"];
                        "application/json": components["schemas"]["AuthResponse"];
                        "text/json": components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponse"];
                        "application/json": components["schemas"]["AuthResponse"];
                        "text/json": components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/food/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FoodItemDto"][];
                        "application/json": components["schemas"]["FoodItemDto"][];
                        "text/json": components["schemas"]["FoodItemDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/food/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meal-diary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MealDiaryDto"][];
                        "application/json": components["schemas"]["MealDiaryDto"][];
                        "text/json": components["schemas"]["MealDiaryDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateMealDiaryRequest"];
                    "text/json": components["schemas"]["CreateMealDiaryRequest"];
                    "application/*+json": components["schemas"]["CreateMealDiaryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MealDiaryDto"];
                        "application/json": components["schemas"]["MealDiaryDto"];
                        "text/json": components["schemas"]["MealDiaryDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meal-diary/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MealDiaryDto"];
                        "application/json": components["schemas"]["MealDiaryDto"];
                        "text/json": components["schemas"]["MealDiaryDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateMealDiaryRequest"];
                    "text/json": components["schemas"]["UpdateMealDiaryRequest"];
                    "application/*+json": components["schemas"]["UpdateMealDiaryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MealDiaryDto"];
                        "application/json": components["schemas"]["MealDiaryDto"];
                        "text/json": components["schemas"]["MealDiaryDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"];
                        "application/json": components["schemas"]["UserDto"];
                        "text/json": components["schemas"]["UserDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserDto"];
                    "text/json": components["schemas"]["UserDto"];
                    "application/*+json": components["schemas"]["UserDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"];
                        "application/json": components["schemas"]["UserDto"];
                        "text/json": components["schemas"]["UserDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthResponse: {
            /** Format: uuid */
            userId?: string;
            email?: string | null;
            displayName?: string | null;
            token?: string | null;
            /** Format: date-time */
            expiresAt?: string;
        };
        CreateMealDiaryRequest: {
            /** Format: date-time */
            eatenDate?: string;
            /** Format: int32 */
            mealTypeId?: number;
            /** Format: int32 */
            foodItemId?: number | null;
            /** Format: int32 */
            userDishId?: number | null;
            /** Format: int32 */
            recipeId?: number | null;
            /** Format: int32 */
            servingUnitId?: number | null;
            /** Format: double */
            portionQuantity?: number | null;
            /** Format: double */
            grams?: number;
            /** Format: double */
            calories?: number;
            /** Format: double */
            protein?: number;
            /** Format: double */
            carb?: number;
            /** Format: double */
            fat?: number;
            note?: string | null;
            photoUrl?: string | null;
            sourceMethod?: string | null;
        };
        FoodItemDto: {
            /** Format: int32 */
            foodItemId?: number;
            foodName?: string | null;
            /** Format: double */
            caloriesPer100g?: number;
            /** Format: double */
            proteinPer100g?: number;
            /** Format: double */
            carbPer100g?: number;
            /** Format: double */
            fatPer100g?: number;
            isActive?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            servings?: components["schemas"]["FoodServingDto"][] | null;
        };
        FoodServingDto: {
            /** Format: int32 */
            foodServingId?: number;
            /** Format: int32 */
            servingUnitId?: number;
            servingUnitName?: string | null;
            servingUnitSymbol?: string | null;
            /** Format: double */
            gramsPerUnit?: number;
            description?: string | null;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        MealDiaryDto: {
            /** Format: int32 */
            mealDiaryId?: number;
            /** Format: uuid */
            userId?: string;
            /** Format: date-time */
            eatenDate?: string;
            /** Format: int32 */
            mealTypeId?: number;
            mealTypeName?: string | null;
            /** Format: int32 */
            foodItemId?: number | null;
            foodItemName?: string | null;
            /** Format: int32 */
            userDishId?: number | null;
            userDishName?: string | null;
            /** Format: int32 */
            recipeId?: number | null;
            recipeName?: string | null;
            /** Format: int32 */
            servingUnitId?: number | null;
            servingUnitName?: string | null;
            servingUnitSymbol?: string | null;
            /** Format: double */
            portionQuantity?: number | null;
            /** Format: double */
            grams?: number;
            /** Format: double */
            calories?: number;
            /** Format: double */
            protein?: number;
            /** Format: double */
            carb?: number;
            /** Format: double */
            fat?: number;
            note?: string | null;
            photoUrl?: string | null;
            sourceMethod?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            isDeleted?: boolean;
        };
        NutritionSummaryDto: {
            /** Format: double */
            totalCalories?: number;
            /** Format: double */
            totalProtein?: number;
            /** Format: double */
            totalCarbs?: number;
            /** Format: double */
            totalFat?: number;
            caloriesByMealType?: {
                [key: string]: number;
            } | null;
            dailyCalories?: {
                [key: string]: number;
            } | null;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            displayName: string;
        };
        UpdateMealDiaryRequest: {
            /** Format: date-time */
            eatenDate?: string | null;
            /** Format: int32 */
            mealTypeId?: number | null;
            /** Format: int32 */
            foodItemId?: number | null;
            /** Format: int32 */
            userDishId?: number | null;
            /** Format: int32 */
            recipeId?: number | null;
            /** Format: int32 */
            servingUnitId?: number | null;
            /** Format: double */
            portionQuantity?: number | null;
            /** Format: double */
            grams?: number | null;
            /** Format: double */
            calories?: number | null;
            /** Format: double */
            protein?: number | null;
            /** Format: double */
            carb?: number | null;
            /** Format: double */
            fat?: number | null;
            note?: string | null;
            photoUrl?: string | null;
            sourceMethod?: string | null;
        };
        UserDto: {
            /** Format: uuid */
            userId?: string;
            email?: string | null;
            displayName?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
