import type { MoChiPoseKey } from '../../assets/mascot/mochi/mochiAssets';
import {
  MOCHI_EVENT_TO_POSE,
  type MoChiPetEventType,
  type MoChiPetMood,
  type MoChiPrimaryAction,
} from './mochiPoseCatalog';

export type MoChiExperienceDomain =
  | 'onboarding'
  | 'logging'
  | 'scan'
  | 'voice'
  | 'recipe'
  | 'progress'
  | 'profile'
  | 'health'
  | 'system'
  | 'companion';

export type MoChiPoseRoleKey =
  | 'pose_angry'
  | 'pose_sad_cry'
  | 'pose_confused'
  | 'pose_calm'
  | 'pose_analyzing'
  | 'pose_hydrate'
  | 'pose_face_surprised'
  | 'pose_face_sad'
  | 'pose_face_tired'
  | 'pose_face_thinking'
  | 'pose_face_calm'
  | 'pose_food_scale'
  | 'pose_cake_concern'
  | 'pose_tablet_meal'
  | 'pose_carb_explain'
  | 'pose_spin_choice'
  | 'pose_logout_notice'
  | 'pose_scan_success_face'
  | 'pose_scan_uncertain_face'
  | 'pose_secure_face';

export type MoChiExperienceCatalogKey = MoChiPetEventType | MoChiPoseRoleKey;

export type MoChiExperienceEntry = {
  eventType: MoChiExperienceCatalogKey;
  poseKey: MoChiPoseKey;
  domain: MoChiExperienceDomain;
  mood: MoChiPetMood;
  title: string;
  dialogue: string;
  primaryAction: MoChiPrimaryAction;
  ctaLabel?: string;
  priority: number;
  shouldBubble: boolean;
};

const entry = (
  eventType: MoChiPetEventType,
  options: Omit<MoChiExperienceEntry, 'eventType' | 'poseKey'>,
): MoChiExperienceEntry => ({
  eventType,
  poseKey: MOCHI_EVENT_TO_POSE[eventType],
  ...options,
});

const roleEntry = (
  eventType: MoChiPoseRoleKey,
  poseKey: MoChiPoseKey,
  options: Omit<MoChiExperienceEntry, 'eventType' | 'poseKey'>,
): MoChiExperienceEntry => ({
  eventType,
  poseKey,
  ...options,
});

export const REQUIRED_MOCHI_CONTEXT_EVENTS: MoChiPetEventType[] = [
  'tutorial_welcome',
  'tutorial_scan',
  'tutorial_search',
  'tutorial_water',
  'tutorial_progress',
  'diary_empty_today',
  'food_search_empty',
  'food_search_no_results',
  'food_search_error',
  'scan_processing',
  'scan_success',
  'scan_empty',
  'scan_error',
  'meal_logged',
  'voice_idle',
  'voice_listening',
  'voice_review',
  'voice_success',
  'voice_error',
  'recipe_empty',
  'recipe_searching',
  'recipe_success',
  'recipe_error',
  'stats_low_data',
  'weekly_review',
  'achievement_unlocked',
  'profile_incomplete',
  'weight_checkin',
  'nutrition_targets',
  'app_offline',
  'generic_error',
];

export const MOCHI_EXPERIENCE_CATALOG: Record<MoChiExperienceCatalogKey, MoChiExperienceEntry> = {
  app_idle: entry('app_idle', {
    domain: 'companion',
    mood: 'idle',
    title: 'MoChi sẵn sàng',
    dialogue: 'Mình đang canh nhịp ngày của bạn. Cần ghi bữa, uống nước hay xem tiến độ thì chạm MoChi nhé.',
    primaryAction: 'scanFood',
    ctaLabel: 'Quét món',
    priority: 1,
    shouldBubble: false,
  }),
  tutorial_step: entry('tutorial_step', {
    domain: 'onboarding',
    mood: 'celebrating',
    title: 'Đi từng bước',
    dialogue: 'MoChi sẽ chỉ dẫn bằng hành động nhỏ, không bắt bạn học hết app trong một lần.',
    primaryAction: 'dismiss',
    ctaLabel: 'Tiếp tục',
    priority: 4,
    shouldBubble: true,
  }),
  tutorial_welcome: entry('tutorial_welcome', {
    domain: 'onboarding',
    mood: 'idle',
    title: 'Gặp MoChi',
    dialogue: 'Mục tiêu đầu tiên là ghi được một bữa thật nhanh. Khi có dữ liệu, MoChi mới tư vấn đúng hơn.',
    primaryAction: 'addMeal',
    ctaLabel: 'Bắt đầu',
    priority: 6,
    shouldBubble: true,
  }),
  tutorial_scan: entry('tutorial_scan', {
    domain: 'onboarding',
    mood: 'hungry',
    title: 'Quét khi muốn nhanh',
    dialogue: 'Chụp món ăn để có gợi ý ban đầu, rồi kiểm tra khẩu phần trước khi lưu.',
    primaryAction: 'scanFood',
    ctaLabel: 'Quét món',
    priority: 6,
    shouldBubble: true,
  }),
  tutorial_search: entry('tutorial_search', {
    domain: 'onboarding',
    mood: 'thinking',
    title: 'Tìm khi cần chắc',
    dialogue: 'Nếu ảnh khó nhận diện, tìm món thủ công sẽ giúp nhật ký chính xác và ít bực hơn.',
    primaryAction: 'addMeal',
    ctaLabel: 'Tìm món',
    priority: 6,
    shouldBubble: true,
  }),
  tutorial_water: entry('tutorial_water', {
    domain: 'onboarding',
    mood: 'thirsty',
    title: 'Một nhịp nước',
    dialogue: 'Nước là hành động nhỏ dễ thắng. Ghi một ly để MoChi hiểu nhịp sinh hoạt hôm nay.',
    primaryAction: 'water',
    ctaLabel: 'Ghi nước',
    priority: 6,
    shouldBubble: true,
  }),
  tutorial_progress: entry('tutorial_progress', {
    domain: 'onboarding',
    mood: 'reporting',
    title: 'Xem bức tranh tổng',
    dialogue: 'Sau vài lần ghi, báo cáo sẽ chuyển từ số liệu rời rạc thành gợi ý hành động.',
    primaryAction: 'viewProgress',
    ctaLabel: 'Xem tiến độ',
    priority: 6,
    shouldBubble: true,
  }),
  meal_reminder: entry('meal_reminder', {
    domain: 'logging',
    mood: 'hungry',
    title: 'Thiếu một bữa',
    dialogue: 'Bữa này chưa thấy trong nhật ký. Ghi nhanh để kế hoạch hôm nay còn có điểm tựa.',
    primaryAction: 'addMeal',
    ctaLabel: 'Ghi bữa',
    priority: 8,
    shouldBubble: true,
  }),
  water_reminder: entry('water_reminder', {
    domain: 'health',
    mood: 'thirsty',
    title: 'Đến lượt uống nước',
    dialogue: 'Tạm dừng vài giây uống nước nha. MoChi thấy nhịp nước hôm nay hơi thấp.',
    primaryAction: 'water',
    ctaLabel: 'Thêm nước',
    priority: 7,
    shouldBubble: true,
  }),
  scan_processing: entry('scan_processing', {
    domain: 'scan',
    mood: 'thinking',
    title: 'Đang phân tích',
    dialogue: 'MoChi đang soi món này. Chờ một nhịp để kiểm tra kết quả trước khi lưu nhé.',
    primaryAction: 'scanFood',
    ctaLabel: 'Đang quét',
    priority: 9,
    shouldBubble: true,
  }),
  scan_success: entry('scan_success', {
    domain: 'scan',
    mood: 'happy',
    title: 'Nhận diện được rồi',
    dialogue: 'Kết quả đã có. Kiểm tra khẩu phần một chút để nhật ký đáng tin hơn.',
    primaryAction: 'addMeal',
    ctaLabel: 'Xem kết quả',
    priority: 8,
    shouldBubble: true,
  }),
  scan_empty: entry('scan_empty', {
    domain: 'scan',
    mood: 'confused',
    title: 'Ảnh hơi khó đọc',
    dialogue: 'MoChi chưa nhìn ra món. Chụp rõ hơn hoặc tìm thủ công sẽ chắc hơn.',
    primaryAction: 'scanFood',
    ctaLabel: 'Chụp lại',
    priority: 9,
    shouldBubble: true,
  }),
  scan_error: entry('scan_error', {
    domain: 'scan',
    mood: 'error',
    title: 'Quét bị lỗi',
    dialogue: 'Có lỗi khi xử lý ảnh. Thử lại sau vài giây, MoChi vẫn canh tiếp ở đây.',
    primaryAction: 'scanFood',
    ctaLabel: 'Thử lại',
    priority: 10,
    shouldBubble: true,
  }),
  meal_logged: entry('meal_logged', {
    domain: 'logging',
    mood: 'happy',
    title: 'Đã ghi bữa',
    dialogue: 'Tốt rồi. Một bữa được ghi đúng sẽ làm báo cáo hôm nay đáng tin hơn nhiều.',
    primaryAction: 'viewDiary',
    ctaLabel: 'Xem nhật ký',
    priority: 6,
    shouldBubble: true,
  }),
  diary_empty_today: entry('diary_empty_today', {
    domain: 'logging',
    mood: 'thinking',
    title: 'Nhật ký còn trống',
    dialogue: 'Bắt đầu bằng món gần nhất. Bạn có thể quét ảnh hoặc tìm món thủ công.',
    primaryAction: 'addMeal',
    ctaLabel: 'Ghi món đầu tiên',
    priority: 5,
    shouldBubble: false,
  }),
  diary_review: entry('diary_review', {
    domain: 'logging',
    mood: 'reporting',
    title: 'Rà lại hôm nay',
    dialogue: 'Nhìn lại một lượt giúp MoChi phát hiện bữa thiếu hoặc khẩu phần cần sửa.',
    primaryAction: 'viewDiary',
    ctaLabel: 'Mở nhật ký',
    priority: 4,
    shouldBubble: false,
  }),
  food_search_empty: entry('food_search_empty', {
    domain: 'logging',
    mood: 'thinking',
    title: 'Bạn muốn ăn gì?',
    dialogue: 'Gõ tên món, nguyên liệu hoặc thương hiệu. MoChi sẽ giúp chọn kết quả gần nhất.',
    primaryAction: 'addMeal',
    ctaLabel: 'Tìm món',
    priority: 5,
    shouldBubble: false,
  }),
  food_search_no_results: entry('food_search_no_results', {
    domain: 'logging',
    mood: 'confused',
    title: 'Chưa thấy món này',
    dialogue: 'Thử tên ngắn hơn hoặc tạo món nhà làm để lần sau ghi nhanh hơn.',
    primaryAction: 'addMeal',
    ctaLabel: 'Tạo món',
    priority: 6,
    shouldBubble: false,
  }),
  food_search_error: entry('food_search_error', {
    domain: 'system',
    mood: 'error',
    title: 'Tìm kiếm bị lỗi',
    dialogue: 'Kết nối tìm món đang không ổn. Thử lại hoặc ghi thủ công phần quan trọng trước.',
    primaryAction: 'addMeal',
    ctaLabel: 'Thử lại',
    priority: 8,
    shouldBubble: true,
  }),
  voice_idle: entry('voice_idle', {
    domain: 'voice',
    mood: 'idle',
    title: 'Nói hoặc gõ lệnh',
    dialogue: 'Bạn có thể nói “thêm 1 bát phở bữa trưa” hoặc gõ trực tiếp nếu đang ở nơi ồn.',
    primaryAction: 'dismiss',
    ctaLabel: 'Thử lệnh',
    priority: 4,
    shouldBubble: false,
  }),
  voice_listening: entry('voice_listening', {
    domain: 'voice',
    mood: 'thinking',
    title: 'MoChi đang nghe',
    dialogue: 'Nói ngắn gọn món, lượng và bữa. Càng rõ thì bước kiểm tra càng nhanh.',
    primaryAction: 'dismiss',
    ctaLabel: 'Đang nghe',
    priority: 6,
    shouldBubble: false,
  }),
  voice_review: entry('voice_review', {
    domain: 'voice',
    mood: 'thinking',
    title: 'Kiểm tra trước khi lưu',
    dialogue: 'MoChi đã hiểu lệnh. Rà lại món và khẩu phần trước khi bấm thực hiện.',
    primaryAction: 'dismiss',
    ctaLabel: 'Kiểm tra',
    priority: 7,
    shouldBubble: false,
  }),
  voice_success: entry('voice_success', {
    domain: 'voice',
    mood: 'happy',
    title: 'Lệnh đã xong',
    dialogue: 'Đã cập nhật nhật ký. Một câu ngắn cũng đủ giữ dữ liệu hôm nay liền mạch.',
    primaryAction: 'viewDiary',
    ctaLabel: 'Xem nhật ký',
    priority: 6,
    shouldBubble: true,
  }),
  voice_error: entry('voice_error', {
    domain: 'voice',
    mood: 'error',
    title: 'MoChi chưa hiểu rõ',
    dialogue: 'Thử nói ngắn hơn: món ăn, số lượng, rồi bữa ăn. Ví dụ “200g cơm bữa trưa”.',
    primaryAction: 'dismiss',
    ctaLabel: 'Thử lại',
    priority: 8,
    shouldBubble: true,
  }),
  recipe_empty: entry('recipe_empty', {
    domain: 'recipe',
    mood: 'idle',
    title: 'Có nguyên liệu nào?',
    dialogue: 'Nhập vài nguyên liệu đang có. MoChi sẽ gợi ý món dễ nấu trước.',
    primaryAction: 'dismiss',
    ctaLabel: 'Nhập nguyên liệu',
    priority: 4,
    shouldBubble: false,
  }),
  recipe_searching: entry('recipe_searching', {
    domain: 'recipe',
    mood: 'thinking',
    title: 'Đang ghép món',
    dialogue: 'MoChi đang tìm công thức hợp nguyên liệu và mục tiêu dinh dưỡng của bạn.',
    primaryAction: 'dismiss',
    ctaLabel: 'Đang tìm',
    priority: 6,
    shouldBubble: false,
  }),
  recipe_success: entry('recipe_success', {
    domain: 'recipe',
    mood: 'happy',
    title: 'Có món phù hợp',
    dialogue: 'Chọn công thức vừa sức trước. Nấu được mới là kế hoạch tốt.',
    primaryAction: 'dismiss',
    ctaLabel: 'Xem công thức',
    priority: 5,
    shouldBubble: false,
  }),
  recipe_error: entry('recipe_error', {
    domain: 'recipe',
    mood: 'error',
    title: 'Chưa tìm được công thức',
    dialogue: 'Thử bớt nguyên liệu hoặc đổi cách gọi món. MoChi sẽ tìm lại gọn hơn.',
    primaryAction: 'dismiss',
    ctaLabel: 'Sửa nguyên liệu',
    priority: 7,
    shouldBubble: false,
  }),
  stats_low_data: entry('stats_low_data', {
    domain: 'progress',
    mood: 'idle',
    title: 'Dữ liệu còn mỏng',
    dialogue: 'Báo cáo sẽ đáng tin hơn khi có vài ngày ghi đủ bữa. Hôm nay chỉ cần thêm một bữa.',
    primaryAction: 'addMeal',
    ctaLabel: 'Ghi bữa',
    priority: 5,
    shouldBubble: false,
  }),
  weekly_review: entry('weekly_review', {
    domain: 'progress',
    mood: 'reporting',
    title: 'Có tín hiệu tuần',
    dialogue: 'MoChi sẽ ưu tiên một hành động nhỏ thay vì bắt bạn đọc cả đống số.',
    primaryAction: 'viewProgress',
    ctaLabel: 'Xem review',
    priority: 5,
    shouldBubble: true,
  }),
  achievement_unlocked: entry('achievement_unlocked', {
    domain: 'progress',
    mood: 'celebrating',
    title: 'Mở khóa thành tích',
    dialogue: 'Nhịp tốt đang hình thành. Tự hào một chút rồi mình giữ tiếp ngày mai.',
    primaryAction: 'viewProgress',
    ctaLabel: 'Xem huy hiệu',
    priority: 6,
    shouldBubble: true,
  }),
  profile_incomplete: entry('profile_incomplete', {
    domain: 'profile',
    mood: 'confused',
    title: 'Hồ sơ còn thiếu',
    dialogue: 'Chiều cao, cân nặng và mục tiêu giúp MoChi tính gợi ý thực tế hơn.',
    primaryAction: 'dismiss',
    ctaLabel: 'Cập nhật',
    priority: 5,
    shouldBubble: false,
  }),
  weight_checkin: entry('weight_checkin', {
    domain: 'health',
    mood: 'reporting',
    title: 'Cân nặng là tín hiệu',
    dialogue: 'Ghi cân nặng đều giúp xem xu hướng, không phải để phán xét từng ngày.',
    primaryAction: 'dismiss',
    ctaLabel: 'Ghi cân nặng',
    priority: 5,
    shouldBubble: false,
  }),
  nutrition_targets: entry('nutrition_targets', {
    domain: 'health',
    mood: 'thinking',
    title: 'Chỉnh mục tiêu',
    dialogue: 'Mục tiêu tốt nên vừa sức. MoChi sẽ giải thích trước khi bạn áp dụng.',
    primaryAction: 'dismiss',
    ctaLabel: 'Xem mục tiêu',
    priority: 5,
    shouldBubble: false,
  }),
  nutrition_explain: entry('nutrition_explain', {
    domain: 'health',
    mood: 'thinking',
    title: 'Giải thích macro',
    dialogue: 'Carb, đạm và chất béo nên phục vụ bữa ăn thật, không biến thành áp lực.',
    primaryAction: 'dismiss',
    ctaLabel: 'Xem giải thích',
    priority: 4,
    shouldBubble: false,
  }),
  hydration_goal: entry('hydration_goal', {
    domain: 'health',
    mood: 'thirsty',
    title: 'Mục tiêu nước',
    dialogue: 'Chia nhỏ lượng nước trong ngày dễ hơn là cố bù một lần vào buổi tối.',
    primaryAction: 'water',
    ctaLabel: 'Thêm nước',
    priority: 4,
    shouldBubble: false,
  }),
  meal_choice: entry('meal_choice', {
    domain: 'logging',
    mood: 'thinking',
    title: 'Chọn bữa phù hợp',
    dialogue: 'Ghi đúng bữa giúp báo cáo đọc nhịp ăn chính xác hơn.',
    primaryAction: 'addMeal',
    ctaLabel: 'Chọn bữa',
    priority: 4,
    shouldBubble: false,
  }),
  workout_nudge: entry('workout_nudge', {
    domain: 'health',
    mood: 'celebrating',
    title: 'Có vận động',
    dialogue: 'Vận động là ngữ cảnh tốt cho bữa ăn, nhưng mình vẫn giữ trọng tâm ở dinh dưỡng.',
    primaryAction: 'viewProgress',
    ctaLabel: 'Xem tiến độ',
    priority: 3,
    shouldBubble: false,
  }),
  favorite_saved: entry('favorite_saved', {
    domain: 'logging',
    mood: 'happy',
    title: 'Đã lưu món quen',
    dialogue: 'Món quen được lưu sẽ làm lần ghi sau nhanh hơn nhiều.',
    primaryAction: 'addMeal',
    ctaLabel: 'Ghi tiếp',
    priority: 4,
    shouldBubble: false,
  }),
  cooking_prep: entry('cooking_prep', {
    domain: 'recipe',
    mood: 'thinking',
    title: 'Chuẩn bị bữa',
    dialogue: 'Chọn món dễ làm trước. Kế hoạch tốt là kế hoạch bạn thật sự nấu được.',
    primaryAction: 'dismiss',
    ctaLabel: 'Chuẩn bị',
    priority: 4,
    shouldBubble: false,
  }),
  diet_warning: entry('diet_warning', {
    domain: 'health',
    mood: 'concerned',
    title: 'Cẩn thận với ăn kiêng gắt',
    dialogue: 'Nếu mục tiêu quá căng, MoChi sẽ nhắc nhẹ để bạn chọn cách bền hơn.',
    primaryAction: 'dismiss',
    ctaLabel: 'Xem lại',
    priority: 7,
    shouldBubble: true,
  }),
  companion_rest: entry('companion_rest', {
    domain: 'companion',
    mood: 'idle',
    title: 'Nhịp bình tĩnh',
    dialogue: 'Không cần hoàn hảo. Ghi đều và sửa được mới là nhịp tốt.',
    primaryAction: 'dismiss',
    ctaLabel: 'Đã hiểu',
    priority: 2,
    shouldBubble: false,
  }),
  companion_love: entry('companion_love', {
    domain: 'companion',
    mood: 'happy',
    title: 'Món bạn thích',
    dialogue: 'Ăn uống bền vững vẫn có chỗ cho món yêu thích, miễn là mình ghi rõ.',
    primaryAction: 'addMeal',
    ctaLabel: 'Ghi món',
    priority: 3,
    shouldBubble: false,
  }),
  companion_determined: entry('companion_determined', {
    domain: 'companion',
    mood: 'celebrating',
    title: 'Giữ nhịp',
    dialogue: 'Một hành động nhỏ hôm nay đáng hơn một kế hoạch rất đẹp nhưng bỏ dở.',
    primaryAction: 'addMeal',
    ctaLabel: 'Làm bước nhỏ',
    priority: 3,
    shouldBubble: false,
  }),
  companion_surprised: entry('companion_surprised', {
    domain: 'companion',
    mood: 'confused',
    title: 'Có gì lạ rồi',
    dialogue: 'Khi dữ liệu khác thường, MoChi sẽ hỏi lại thay vì đoán quá tự tin.',
    primaryAction: 'dismiss',
    ctaLabel: 'Kiểm tra',
    priority: 5,
    shouldBubble: false,
  }),
  companion_embarrassed: entry('companion_embarrassed', {
    domain: 'companion',
    mood: 'confused',
    title: 'Không sao cả',
    dialogue: 'Lỡ quên ghi cũng bình thường. Mình ghi lại từ bữa gần nhất là đủ.',
    primaryAction: 'addMeal',
    ctaLabel: 'Ghi bữa gần nhất',
    priority: 4,
    shouldBubble: false,
  }),
  companion_strained: entry('companion_strained', {
    domain: 'system',
    mood: 'error',
    title: 'Đang hơi quá tải',
    dialogue: 'Nếu app phản hồi chậm, thử lại một lần. MoChi sẽ giữ hướng đi ngắn nhất.',
    primaryAction: 'dismiss',
    ctaLabel: 'Thử lại',
    priority: 6,
    shouldBubble: true,
  }),
  companion_box_idle: entry('companion_box_idle', {
    domain: 'companion',
    mood: 'idle',
    title: 'MoChi ở đây',
    dialogue: 'Chạm MoChi khi bạn muốn chọn nhanh giữa quét món, tìm món, công thức và nước.',
    primaryAction: 'scanFood',
    ctaLabel: 'Mở trợ lý',
    priority: 2,
    shouldBubble: false,
  }),
  app_offline: entry('app_offline', {
    domain: 'system',
    mood: 'error',
    title: 'Kết nối chưa ổn',
    dialogue: 'Bạn vẫn có thể chuẩn bị dữ liệu cần ghi. Khi mạng ổn, thử lại thao tác chính.',
    primaryAction: 'dismiss',
    ctaLabel: 'Thử lại',
    priority: 8,
    shouldBubble: true,
  }),
  generic_error: entry('generic_error', {
    domain: 'system',
    mood: 'error',
    title: 'Có lỗi xảy ra',
    dialogue: 'MoChi không đoán mò. Thử lại thao tác vừa rồi hoặc quay về màn chính.',
    primaryAction: 'dismiss',
    ctaLabel: 'Thử lại',
    priority: 9,
    shouldBubble: true,
  }),
  water_added: entry('water_added', {
    domain: 'health',
    mood: 'thirsty',
    title: 'Đã thêm nước',
    dialogue: 'Nhịp nhỏ thôi nhưng cả ngày sẽ dễ thở hơn. Tiếp tục chia nhỏ như vậy nhé.',
    primaryAction: 'water',
    ctaLabel: 'Thêm tiếp',
    priority: 5,
    shouldBubble: true,
  }),
  streak_unlocked: entry('streak_unlocked', {
    domain: 'progress',
    mood: 'celebrating',
    title: 'Streak đang lên',
    dialogue: 'Bạn đang tạo nhịp tốt. MoChi cho phép tự hào một chút rồi mình giữ tiếp.',
    primaryAction: 'viewProgress',
    ctaLabel: 'Xem thành tích',
    priority: 6,
    shouldBubble: true,
  }),
  calorie_caution: entry('calorie_caution', {
    domain: 'health',
    mood: 'concerned',
    title: 'Calo hơi vượt nhịp',
    dialogue: 'Không sao. Ghi tiếp để MoChi cân lại phần sau, đừng bỏ trống nhật ký.',
    primaryAction: 'addMeal',
    ctaLabel: 'Ghi tiếp',
    priority: 7,
    shouldBubble: true,
  }),
  report_ready: entry('report_ready', {
    domain: 'progress',
    mood: 'reporting',
    title: 'Có báo cáo mới',
    dialogue: 'MoChi mở ra để bạn xem bức tranh tổng, rồi chọn một hành động nhỏ.',
    primaryAction: 'viewProgress',
    ctaLabel: 'Xem báo cáo',
    priority: 4,
    shouldBubble: true,
  }),
  pose_angry: roleEntry('pose_angry', 'angry', {
    domain: 'system',
    mood: 'concerned',
    title: 'Cảnh báo rõ ràng',
    dialogue: 'Dành cho trạng thái cần ngắt thao tác nguy hiểm và nhắc người dùng kiểm tra lại.',
    primaryAction: 'dismiss',
    priority: 1,
    shouldBubble: false,
  }),
  pose_sad_cry: roleEntry('pose_sad_cry', 'sadCry', {
    domain: 'system',
    mood: 'error',
    title: 'Lỗi cần xin lỗi',
    dialogue: 'Dành cho lỗi xử lý làm người dùng phải thử lại, với giọng mềm thay vì gây hoảng.',
    primaryAction: 'dismiss',
    priority: 1,
    shouldBubble: false,
  }),
  pose_confused: roleEntry('pose_confused', 'confused', {
    domain: 'scan',
    mood: 'confused',
    title: 'Chưa chắc kết quả',
    dialogue: 'Dành cho tình huống MoChi cần hỏi lại trước khi đưa ra gợi ý dinh dưỡng.',
    primaryAction: 'scanFood',
    priority: 1,
    shouldBubble: false,
  }),
  pose_calm: roleEntry('pose_calm', 'calm', {
    domain: 'companion',
    mood: 'idle',
    title: 'Nghỉ nhẹ',
    dialogue: 'Dành cho khoảnh khắc không có việc gấp nhưng vẫn muốn MoChi hiện diện dịu mắt.',
    primaryAction: 'dismiss',
    priority: 1,
    shouldBubble: false,
  }),
  pose_analyzing: roleEntry('pose_analyzing', 'analyzing', {
    domain: 'scan',
    mood: 'thinking',
    title: 'Đang xử lý nền',
    dialogue: 'Dành cho trạng thái phân tích cũ khi cần giữ tương thích với sprite hiện có.',
    primaryAction: 'scanFood',
    priority: 1,
    shouldBubble: false,
  }),
  pose_hydrate: roleEntry('pose_hydrate', 'hydrate', {
    domain: 'health',
    mood: 'thirsty',
    title: 'Nhắc nước gọn',
    dialogue: 'Dành cho lời nhắc uống nước dạng nhỏ, không chiếm nhiều không gian màn hình.',
    primaryAction: 'water',
    priority: 1,
    shouldBubble: false,
  }),
  pose_face_surprised: roleEntry('pose_face_surprised', 'faceSurprised', {
    domain: 'voice',
    mood: 'thinking',
    title: 'Nghe thấy tín hiệu',
    dialogue: 'Dành cho phản hồi nhanh khi người dùng vừa bắt đầu nói hoặc đưa dữ liệu mới.',
    primaryAction: 'dismiss',
    priority: 1,
    shouldBubble: false,
  }),
  pose_face_sad: roleEntry('pose_face_sad', 'faceSad', {
    domain: 'companion',
    mood: 'error',
    title: 'Tiếc nhẹ',
    dialogue: 'Dành cho trạng thái lỗi nhỏ khi MoChi cần nhận lỗi mà không làm nặng trải nghiệm.',
    primaryAction: 'dismiss',
    priority: 1,
    shouldBubble: false,
  }),
  pose_face_tired: roleEntry('pose_face_tired', 'faceTired', {
    domain: 'system',
    mood: 'concerned',
    title: 'Mạng chưa ổn',
    dialogue: 'Dành cho trạng thái chờ mạng hoặc tác vụ chậm cần thông báo một cách bình tĩnh.',
    primaryAction: 'dismiss',
    priority: 1,
    shouldBubble: false,
  }),
  pose_face_thinking: roleEntry('pose_face_thinking', 'faceThinking', {
    domain: 'logging',
    mood: 'thinking',
    title: 'Đang cân nhắc',
    dialogue: 'Dành cho bước cần người dùng xác nhận khẩu phần, món ăn hoặc lựa chọn tiếp theo.',
    primaryAction: 'addMeal',
    priority: 1,
    shouldBubble: false,
  }),
  pose_face_calm: roleEntry('pose_face_calm', 'faceCalm', {
    domain: 'companion',
    mood: 'idle',
    title: 'Bình tĩnh',
    dialogue: 'Dành cho các màn hình cần sự yên tâm, ít chuyển động và ít tạo áp lực.',
    primaryAction: 'dismiss',
    priority: 1,
    shouldBubble: false,
  }),
  pose_food_scale: roleEntry('pose_food_scale', 'foodScale', {
    domain: 'health',
    mood: 'thinking',
    title: 'Cân bằng dinh dưỡng',
    dialogue: 'Dành cho phần giải thích mục tiêu dinh dưỡng hoặc điều chỉnh khẩu phần.',
    primaryAction: 'addMeal',
    priority: 1,
    shouldBubble: false,
  }),
  pose_cake_concern: roleEntry('pose_cake_concern', 'cakeConcern', {
    domain: 'health',
    mood: 'concerned',
    title: 'Cẩn thận calo',
    dialogue: 'Dành cho lời nhắc nhẹ khi bữa ăn có thể lệch khỏi mục tiêu trong ngày.',
    primaryAction: 'addMeal',
    priority: 1,
    shouldBubble: false,
  }),
  pose_tablet_meal: roleEntry('pose_tablet_meal', 'tabletMeal', {
    domain: 'logging',
    mood: 'hungry',
    title: 'Xem lại bữa',
    dialogue: 'Dành cho màn hình rà soát nhật ký hoặc chỉnh lại thông tin bữa ăn đã ghi.',
    primaryAction: 'viewDiary',
    priority: 1,
    shouldBubble: false,
  }),
  pose_carb_explain: roleEntry('pose_carb_explain', 'carbExplain', {
    domain: 'health',
    mood: 'thinking',
    title: 'Giải thích macro',
    dialogue: 'Dành cho phần hướng dẫn protein, carb và fat bằng ngôn ngữ dễ hiểu.',
    primaryAction: 'dismiss',
    priority: 1,
    shouldBubble: false,
  }),
  pose_spin_choice: roleEntry('pose_spin_choice', 'spinChoice', {
    domain: 'logging',
    mood: 'thinking',
    title: 'Chọn nhanh',
    dialogue: 'Dành cho trạng thái gợi ý nhiều lựa chọn khi người dùng chưa biết ghi món nào.',
    primaryAction: 'addMeal',
    priority: 1,
    shouldBubble: false,
  }),
  pose_logout_notice: roleEntry('pose_logout_notice', 'logoutNotice', {
    domain: 'profile',
    mood: 'idle',
    title: 'Xác nhận tài khoản',
    dialogue: 'Dành cho thao tác đăng xuất hoặc đổi thiết lập tài khoản cần xác nhận rõ ràng.',
    primaryAction: 'dismiss',
    priority: 1,
    shouldBubble: false,
  }),
  pose_scan_success_face: roleEntry('pose_scan_success_face', 'scanSuccessFace', {
    domain: 'scan',
    mood: 'happy',
    title: 'Scan ổn',
    dialogue: 'Dành cho phản hồi nhỏ khi kết quả scan đủ tốt và người dùng chỉ cần kiểm tra lại.',
    primaryAction: 'addMeal',
    priority: 1,
    shouldBubble: false,
  }),
  pose_scan_uncertain_face: roleEntry('pose_scan_uncertain_face', 'scanUncertainFace', {
    domain: 'scan',
    mood: 'confused',
    title: 'Scan chưa chắc',
    dialogue: 'Dành cho phản hồi nhỏ khi MoChi cần người dùng xác nhận món hoặc khẩu phần.',
    primaryAction: 'scanFood',
    priority: 1,
    shouldBubble: false,
  }),
  pose_secure_face: roleEntry('pose_secure_face', 'secureFace', {
    domain: 'profile',
    mood: 'concerned',
    title: 'Bảo mật nhẹ',
    dialogue: 'Dành cho thông báo tài khoản cần sự cẩn trọng nhưng không làm người dùng lo lắng.',
    primaryAction: 'dismiss',
    priority: 1,
    shouldBubble: false,
  }),
};

export const MOCHI_CONTEXT_EVENT_TO_POSE: Record<MoChiPetEventType, MoChiPoseKey> =
  MOCHI_EVENT_TO_POSE;

export const getMoChiExperience = (eventType: MoChiPetEventType): MoChiExperienceEntry =>
  MOCHI_EXPERIENCE_CATALOG[eventType] ?? MOCHI_EXPERIENCE_CATALOG.app_idle;
