import type { MoChiPoseKey } from '../../assets/mascot/mochi/mochiAssets';
import {
  MOCHI_EVENT_TO_POSE,
  type MoChiPetEventType,
  type MoChiPetMood,
  type MoChiPrimaryAction,
} from './mochiPoseCatalog';

export type MoChiExperienceDomain =
  | 'onboarding'
  | 'logging'
  | 'scan'
  | 'voice'
  | 'recipe'
  | 'progress'
  | 'profile'
  | 'health'
  | 'system'
  | 'companion';

export type MoChiPoseRoleKey =
  | 'pose_angry'
  | 'pose_sad_cry'
  | 'pose_confused'
  | 'pose_calm'
  | 'pose_analyzing'
  | 'pose_hydrate'
  | 'pose_face_surprised'
  | 'pose_face_sad'
  | 'pose_face_tired'
  | 'pose_face_thinking'
  | 'pose_face_calm'
  | 'pose_food_scale'
  | 'pose_cake_concern'
  | 'pose_tablet_meal'
  | 'pose_carb_explain'
  | 'pose_spin_choice'
  | 'pose_logout_notice'
  | 'pose_scan_success_face'
  | 'pose_scan_uncertain_face'
  | 'pose_secure_face';

export type MoChiExperienceCatalogKey = MoChiPetEventType | MoChiPoseRoleKey;

export type MoChiExperienceEntry = {
  eventType: MoChiExperienceCatalogKey;
  poseKey: MoChiPoseKey;
  domain: MoChiExperienceDomain;
  mood: MoChiPetMood;
  title: string;
  dialogue: string;
  primaryAction: MoChiPrimaryAction;
  ctaLabel?: string;
  priority: number;
  shouldBubble: boolean;
};

const entry = (
  eventType: MoChiPetEventType,
  options: Omit<MoChiExperienceEntry, 'eventType' | 'poseKey'>,
): MoChiExperienceEntry => ({
  eventType,
  poseKey: MOCHI_EVENT_TO_POSE[eventType],
  ...options,
});

const roleEntry = (
  eventType: MoChiPoseRoleKey,
  poseKey: MoChiPoseKey,
  options: Omit<MoChiExperienceEntry, 'eventType' | 'poseKey'>,
): MoChiExperienceEntry => ({
  eventType,
  poseKey,
  ...options,
});

export const REQUIRED_MOCHI_CONTEXT_EVENTS: MoChiPetEventType[] = [
  'tutorial_welcome',
  'tutorial_scan',
  'tutorial_search',
  'tutorial_water',
  'tutorial_progress',
  'diary_empty_today',
  'food_search_empty',
  'food_search_no_results',
  'food_search_error',
  'scan_processing',
  'scan_success',
  'scan_empty',
  'scan_error',
  'meal_logged',
  'voice_idle',
  'voice_listening',
  'voice_review',
  'voice_success',
  'voice_error',
  'recipe_empty',
  'recipe_searching',
  'recipe_success',
  'recipe_error',
  'stats_low_data',
  'weekly_review',
  'achievement_unlocked',
  'profile_incomplete',
  'weight_checkin',
  'nutrition_targets',
  'app_offline',
  'generic_error',
];

export const MOCHI_EXPERIENCE_CATALOG: Record<MoChiExperienceCatalogKey, MoChiExperienceEntry> = {
  app_idle: entry('app_idle', {
    domain: 'companion',
    mood: 'idle',
    title: 'Tớ ở đây nè! ✨',
    dialogue: 'Hôm nay của bạn thế nào rồi nè? Có món gì ngon hay ly nước mát nào muốn chia sẻ với tớ không ta? Tớ ở đây đợi bạn nhé!',
    primaryAction: 'scanFood',
    ctaLabel: 'Quét món',
    priority: 1,
    shouldBubble: false,
  }),
  tutorial_step: entry('tutorial_step', {
    domain: 'onboarding',
    mood: 'celebrating',
    title: 'Chầm chậm cùng đi nha 🐾',
    dialogue: 'Tụi mình cứ đi từng bước nhỏ thong thả thôi nha, tớ không bắt bạn phải học hết mọi thứ ngay lập tức đâu nè!',
    primaryAction: 'dismiss',
    ctaLabel: 'Tiếp tục',
    priority: 4,
    shouldBubble: true,
  }),
  tutorial_welcome: entry('tutorial_welcome', {
    domain: 'onboarding',
    mood: 'idle',
    title: 'Chào bạn mới đáng yêu! 🥰',
    dialogue: 'Hôm nay tụi mình bắt đầu hành trình cùng nhau rồi đó! Ghi bữa ăn đầu tiên để tớ hiểu thêm về bạn nha!',
    primaryAction: 'addMeal',
    ctaLabel: 'Bắt đầu',
    priority: 6,
    shouldBubble: true,
  }),
  tutorial_scan: entry('tutorial_scan', {
    domain: 'onboarding',
    mood: 'hungry',
    title: 'Chụp ảnh khoe món nha! 📸',
    dialogue: 'Bạn chỉ cần chụp hoặc gửi ảnh món ăn thôi, việc tính toán dinh dưỡng cứ để tớ phụ trách cho nha, siêu nhanh luôn nè!',
    primaryAction: 'scanFood',
    ctaLabel: 'Quét món',
    priority: 6,
    shouldBubble: true,
  }),
  tutorial_search: entry('tutorial_search', {
    domain: 'onboarding',
    mood: 'thinking',
    title: 'Tìm món siêu nhanh nè! 🔍',
    dialogue: 'Nếu món ăn hơi phức tạp một xíu, bạn cứ gõ tên món nha. Cách này giúp tớ ghi chép đầy đủ dưỡng chất cho bạn nhất đó!',
    primaryAction: 'addMeal',
    ctaLabel: 'Tìm món',
    priority: 6,
    shouldBubble: true,
  }),
  tutorial_water: entry('tutorial_water', {
    domain: 'onboarding',
    mood: 'thirsty',
    title: 'Nhấp một ngụm nước mát nha! 💧',
    dialogue: 'Bạn ơi, cơ thể đang khát nước đó nha! Làm một cốc nước mát để tụi mình luôn tràn đầy sức sống đi nè!',
    primaryAction: 'water',
    ctaLabel: 'Ghi nước',
    priority: 6,
    shouldBubble: true,
  }),
  tutorial_progress: entry('tutorial_progress', {
    domain: 'onboarding',
    mood: 'reporting',
    title: 'Nhật ký tiến bộ của tụi mình! 📈',
    dialogue: 'Nhìn lại chặng đường vừa qua mới thấy bạn tuyệt vời thế nào! Tụi mình cùng cố gắng duy trì thói quen tốt mỗi ngày nha!',
    primaryAction: 'viewProgress',
    ctaLabel: 'Xem tiến độ',
    priority: 6,
    shouldBubble: true,
  }),
  meal_reminder: entry('meal_reminder', {
    domain: 'logging',
    mood: 'hungry',
    title: 'Bụng đói reo vang rồi kìa! 🍲',
    dialogue: 'Có phải bạn vừa dùng bữa xong đúng không ta? Kể cho tớ nghe xem hôm nay có món gì ngon và bổ dưỡng thế nhỉ?',
    primaryAction: 'addMeal',
    ctaLabel: 'Ghi bữa',
    priority: 8,
    shouldBubble: true,
  }),
  water_reminder: entry('water_reminder', {
    domain: 'health',
    mood: 'thirsty',
    title: 'Đến giờ tiếp nước rồi nè! 🥤',
    dialogue: 'Nghỉ tay một xíu làm cốc nước mát cho sảng khoái đi nào bạn ơi! Cơ thể đang rất cần nước đó nha!',
    primaryAction: 'water',
    ctaLabel: 'Thêm nước',
    priority: 7,
    shouldBubble: true,
  }),
  scan_processing: entry('scan_processing', {
    domain: 'scan',
    mood: 'thinking',
    title: 'Đang ngắm nghía món ngon... 🧐',
    dialogue: 'Đợi tớ ngắm nghía đĩa thức ăn này một tẹo nha, tớ sẽ phân tích dinh dưỡng thật nhanh cho bạn nè!',
    primaryAction: 'scanFood',
    ctaLabel: 'Đang quét',
    priority: 9,
    shouldBubble: true,
  }),
  scan_success: entry('scan_success', {
    domain: 'scan',
    mood: 'happy',
    title: 'MoChi đoán ra rồi nè! 🎉',
    dialogue: 'Món này trông hấp dẫn quá đi mất! Bạn xem thử tớ đoán các thành phần và khẩu phần đã chuẩn chưa nha.',
    primaryAction: 'addMeal',
    ctaLabel: 'Xem kết quả',
    priority: 8,
    shouldBubble: true,
  }),
  scan_empty: entry('scan_empty', {
    domain: 'scan',
    mood: 'confused',
    title: 'Hình như hơi mờ xíu siêu... 🥺',
    dialogue: 'Ui, góc này tớ hơi khó nhìn một tí xíu. Bạn chụp lại góc khác rõ hơn hoặc gõ tên món ăn giúp tớ nha!',
    primaryAction: 'scanFood',
    ctaLabel: 'Chụp lại',
    priority: 9,
    shouldBubble: true,
  }),
  scan_error: entry('scan_error', {
    domain: 'scan',
    mood: 'error',
    title: 'Ôi, mạng bị nấc cụt rồi! 📡',
    dialogue: 'Hình như đường truyền ảnh đang gặp chút bối rối rồi. Bạn thử gửi lại ảnh hoặc nhập tên món cho tớ nha!',
    primaryAction: 'scanFood',
    ctaLabel: 'Thử lại',
    priority: 10,
    shouldBubble: true,
  }),
  meal_logged: entry('meal_logged', {
    domain: 'logging',
    mood: 'happy',
    title: 'Đã ghi nhớ món ngon nha! ✨',
    dialogue: 'Tuyệt vời quá đi! Chăm chỉ ăn uống khoa học thế này thì mục tiêu khỏe đẹp của bạn chắc chắn sẽ sớm đạt được nè!',
    primaryAction: 'viewDiary',
    ctaLabel: 'Xem nhật ký',
    priority: 6,
    shouldBubble: true,
  }),
  diary_empty_today: entry('diary_empty_today', {
    domain: 'logging',
    mood: 'thinking',
    title: 'Hôm nay ăn gì ngon chưa ta? 🍽️',
    dialogue: 'Ghi nhận ngay bữa ăn gần nhất để tụi mình cùng theo dõi dinh dưỡng nhé!',
    primaryAction: 'addMeal',
    ctaLabel: 'Ghi món đầu tiên nha',
    priority: 5,
    shouldBubble: false,
  }),
  diary_review: entry('diary_review', {
    domain: 'logging',
    mood: 'reporting',
    title: 'Ngày hôm nay của chúng mình! 🌟',
    dialogue: 'Tụi mình cùng nhìn lại thực đơn hôm nay nha! Bạn có muốn điều chỉnh hay bổ sung thêm món ngon nào nữa không nè?',
    primaryAction: 'viewDiary',
    ctaLabel: 'Mở nhật ký',
    priority: 4,
    shouldBubble: false,
  }),
  food_search_empty: entry('food_search_empty', {
    domain: 'logging',
    mood: 'thinking',
    title: 'Thèm món gì cứ nói tớ nhé! 💭',
    dialogue: 'Hãy gõ tên món ăn bạn vừa dùng hoặc muốn tìm để tớ tra cứu thông tin dinh dưỡng cho bạn nha!',
    primaryAction: 'addMeal',
    ctaLabel: 'Tìm món',
    priority: 5,
    shouldBubble: false,
  }),
  food_search_no_results: entry('food_search_no_results', {
    domain: 'logging',
    mood: 'confused',
    title: 'Món này lạ lẫm quá ta... 🤔',
    dialogue: 'Ôi món này mới lạ quá, tớ chưa tìm ra trong thư viện rồi. Bạn thử nhập tên đơn giản hơn hoặc tự tạo món mới nha!',
    primaryAction: 'addMeal',
    ctaLabel: 'Tạo món',
    priority: 6,
    shouldBubble: false,
  }),
  food_search_error: entry('food_search_error', {
    domain: 'system',
    mood: 'error',
    title: 'Hình như tớ tìm hơi lâu xíu... 🐢',
    dialogue: 'Đầu óc tớ tự dưng bận suy nghĩ mông lung một tẹo rồi. Bạn thử tìm lại hoặc tự ước lượng trước giúp tớ nha!',
    primaryAction: 'addMeal',
    ctaLabel: 'Thử lại',
    priority: 8,
    shouldBubble: true,
  }),
  voice_idle: entry('voice_idle', {
    domain: 'voice',
    mood: 'idle',
    title: 'Nói nhỏ tớ nghe đi! 🎙️',
    dialogue: 'Bạn cứ nói tự nhiên như đang trò chuyện tâm sự cùng tớ nhé, ví dụ: "Trưa nay mình ăn một bát phở bò" nè!',
    primaryAction: 'dismiss',
    ctaLabel: 'Thử lệnh',
    priority: 4,
    shouldBubble: false,
  }),
  voice_listening: entry('voice_listening', {
    domain: 'voice',
    mood: 'thinking',
    title: 'Đôi tai nhỏ đang vểnh nghe nè! 👂',
    dialogue: 'Tớ đang chăm chú lắng nghe đây nha! Bạn kể chi tiết hôm nay ăn món gì ngon và ăn bao nhiêu cho tớ nghe với nhé!',
    primaryAction: 'dismiss',
    ctaLabel: 'Đang nghe',
    priority: 6,
    shouldBubble: false,
  }),
  voice_review: entry('voice_review', {
    domain: 'voice',
    mood: 'thinking',
    title: 'Tớ nghe thế này đúng chưa ta? 👀',
    dialogue: 'Tớ ghi chép lại thế này đã đúng ý bạn chưa ta? Bạn xem qua xem có cần điều chỉnh gì lại không nha.',
    primaryAction: 'dismiss',
    ctaLabel: 'Kiểm tra',
    priority: 7,
    shouldBubble: false,
  }),
  voice_success: entry('voice_success', {
    domain: 'voice',
    mood: 'happy',
    title: 'Đã ghi nhớ lời bạn rồi nè! 📝',
    dialogue: 'Thế là xong rồi nè! Ghi chép bằng giọng nói nhanh gọn thế này vừa nhàn vừa giúp tụi mình theo dõi sức khỏe siêu tốt luôn.',
    primaryAction: 'viewDiary',
    ctaLabel: 'Xem nhật ký',
    priority: 6,
    shouldBubble: true,
  }),
  voice_error: entry('voice_error', {
    domain: 'voice',
    mood: 'error',
    title: 'Ơ kìa, tiếng hơi nhỏ xíu... 💨',
    dialogue: 'Giọng bạn vừa rồi nhỏ nhẹ quá nên tớ chưa nghe rõ được nè. Bạn nói to, chậm rãi hơn một tẹo với tớ nha!',
    primaryAction: 'dismiss',
    ctaLabel: 'Thử lại',
    priority: 8,
    shouldBubble: true,
  }),
  recipe_empty: entry('recipe_empty', {
    domain: 'recipe',
    mood: 'idle',
    title: 'Tủ lạnh hôm nay có gì vui? 🥦',
    dialogue: 'Trong bếp hay tủ lạnh nhà bạn đang có sẵn nguyên liệu gì thế nhỉ? Khoe với tớ để tụi mình tìm món ngon nấu ngay nha!',
    primaryAction: 'dismiss',
    ctaLabel: 'Nhập nguyên liệu',
    priority: 4,
    shouldBubble: false,
  }),
  recipe_searching: entry('recipe_searching', {
    domain: 'recipe',
    mood: 'thinking',
    title: 'Đang tìm công thức thần kỳ... 🪄',
    dialogue: 'Đợi tớ một xíu xiu nha! Tớ đang lục tìm những công thức siêu ngon lành và phù hợp nhất với bạn đây rồi.',
    primaryAction: 'dismiss',
    ctaLabel: 'Đang tìm',
    priority: 6,
    shouldBubble: false,
  }),
  recipe_success: entry('recipe_success', {
    domain: 'recipe',
    mood: 'happy',
    title: 'Có món ngon cho bạn rồi nè! 👩‍🍳',
    dialogue: 'Gợi ý món ăn siêu ngon đã ra lò rồi đây! Toàn những công thức hấp dẫn mà lại cực kỳ tốt cho sức khỏe của bạn đó nha.',
    primaryAction: 'dismiss',
    ctaLabel: 'Xem công thức',
    priority: 5,
    shouldBubble: false,
  }),
  recipe_error: entry('recipe_error', {
    domain: 'recipe',
    mood: 'error',
    title: 'Chưa thấy món nào hợp gu rồi... 🥺',
    dialogue: 'Tiếc quá đi mất, tớ chưa tìm thấy món nào phù hợp với nguyên liệu này rồi. Bạn thử thay đổi nguyên liệu khác xem sao nhé!',
    primaryAction: 'dismiss',
    ctaLabel: 'Sửa nguyên liệu',
    priority: 7,
    shouldBubble: false,
  }),
  stats_low_data: entry('stats_low_data', {
    domain: 'progress',
    mood: 'idle',
    title: 'Đang gom góp số liệu nè! 📊',
    dialogue: 'Tụi mình mới đi những bước đầu tiên nên báo cáo chưa được chi tiết lắm nè. Cứ kiên trì ghi chép mỗi ngày cùng tớ nha!',
    primaryAction: 'addMeal',
    ctaLabel: 'Ghi bữa',
    priority: 5,
    shouldBubble: false,
  }),
  weekly_review: entry('weekly_review', {
    domain: 'progress',
    mood: 'reporting',
    title: 'Nhìn lại một tuần rực rỡ! 🌈',
    dialogue: 'Một tuần vừa qua bạn đã cố gắng rất nhiều đó! Tớ có chuẩn bị một vài gợi ý nho nhỏ giúp bạn khỏe mạnh hơn mỗi ngày nè.',
    primaryAction: 'viewProgress',
    ctaLabel: 'Xem review',
    priority: 5,
    shouldBubble: true,
  }),
  achievement_unlocked: entry('achievement_unlocked', {
    domain: 'progress',
    mood: 'celebrating',
    title: 'Bạn siêu cấp xuất sắc luôn! 🏆',
    dialogue: 'Wow, bạn giỏi quá đi mất thôi! Huy hiệu mới toanh lấp lánh đã thuộc về bạn rồi, tiếp tục phát huy nha bạn ơi!',
    primaryAction: 'viewProgress',
    ctaLabel: 'Xem huy hiệu',
    priority: 6,
    shouldBubble: true,
  }),
  profile_incomplete: entry('profile_incomplete', {
    domain: 'profile',
    mood: 'confused',
    title: 'Để MoChi hiểu bạn hơn nha! 💕',
    dialogue: 'Hãy chia sẻ thêm một chút thông tin cá nhân với tớ nha. Càng hiểu rõ về bạn thì tớ gợi ý thực đơn càng chuẩn xác đó!',
    primaryAction: 'dismiss',
    ctaLabel: 'Cập nhật',
    priority: 5,
    shouldBubble: false,
  }),
  weight_checkin: entry('weight_checkin', {
    domain: 'health',
    mood: 'reporting',
    title: 'Ghi nhẹ số cân hôm nay nha! ⚖️',
    dialogue: 'Cân nặng chỉ là những con số tham khảo thôi nè, bạn đừng lo lắng nha! Cứ thoải mái ghi chép để tụi mình theo dõi xu hướng nhé.',
    primaryAction: 'dismiss',
    ctaLabel: 'Ghi cân nặng',
    priority: 5,
    shouldBubble: false,
  }),
  nutrition_targets: entry('nutrition_targets', {
    domain: 'health',
    mood: 'thinking',
    title: 'Mục tiêu nhỏ, bước tiến lớn! 🎯',
    dialogue: 'Mục tiêu tuyệt vời nhất là mục tiêu vừa vặn với sức mình đó. Hãy để tớ đồng hành cùng bạn trên từng bước chân nha!',
    primaryAction: 'dismiss',
    ctaLabel: 'Xem mục tiêu',
    priority: 5,
    shouldBubble: false,
  }),
  nutrition_explain: entry('nutrition_explain', {
    domain: 'health',
    mood: 'thinking',
    title: 'Góc nhỏ dinh dưỡng nè! 🍎',
    dialogue: 'Đạm, carb hay chất béo đều là những người bạn tốt giúp cơ thể khỏe mạnh. Đừng lo lắng hay áp lực quá nha!',
    primaryAction: 'dismiss',
    ctaLabel: 'Xem giải thích',
    priority: 4,
    shouldBubble: false,
  }),
  hydration_goal: entry('hydration_goal', {
    domain: 'health',
    mood: 'thirsty',
    title: 'Bình nước đã đầy chưa ta? 🐳',
    dialogue: 'Uống nước từng ngụm nhỏ suốt cả ngày là bí quyết giữ cho làn da và cơ thể luôn tràn đầy năng lượng tươi trẻ đó!',
    primaryAction: 'water',
    ctaLabel: 'Thêm nước',
    priority: 4,
    shouldBubble: false,
  }),
  meal_choice: entry('meal_choice', {
    domain: 'logging',
    mood: 'thinking',
    title: 'Bữa này là bữa nào nhỉ? 🍱',
    dialogue: 'Bạn ơi, nhớ xếp các món ăn vào đúng bữa nha! Việc này giúp tớ hiểu nhịp sinh hoạt và chăm sóc bạn tốt hơn đó.',
    primaryAction: 'addMeal',
    ctaLabel: 'Chọn bữa',
    priority: 4,
    shouldBubble: false,
  }),
  workout_nudge: entry('workout_nudge', {
    domain: 'health',
    mood: 'celebrating',
    title: 'Bạn tập luyện siêu đỉnh luôn! 🏃‍♂️',
    dialogue: 'Hôm nay bạn có vận động cơ thể đúng không nè? Giỏi quá đi! Nhớ ăn uống đầy đủ dưỡng chất để phục hồi năng lượng nha!',
    primaryAction: 'viewProgress',
    ctaLabel: 'Xem tiến độ',
    priority: 3,
    shouldBubble: false,
  }),
  favorite_saved: entry('favorite_saved', {
    domain: 'logging',
    mood: 'happy',
    title: 'Đã cất món tủ vào kho báu! 💖',
    dialogue: 'Tớ đã lưu món ăn yêu thích của bạn vào góc nhỏ rồi nhé! Từ giờ mỗi lần ăn lại là tìm thấy siêu nhanh và tiện lợi luôn.',
    primaryAction: 'addMeal',
    ctaLabel: 'Ghi tiếp',
    priority: 4,
    shouldBubble: false,
  }),
  cooking_prep: entry('cooking_prep', {
    domain: 'recipe',
    mood: 'thinking',
    title: 'Cùng xắn tay áo vào bếp thôi! 🍳',
    dialogue: 'Hôm nay tụi mình cùng trổ tài nấu nướng nha! Những món ăn tự tay bạn chuẩn bị lúc nào cũng đong đầy tình yêu và dinh dưỡng hết á.',
    primaryAction: 'dismiss',
    ctaLabel: 'Chuẩn bị',
    priority: 4,
    shouldBubble: false,
  }),
  diet_warning: entry('diet_warning', {
    domain: 'health',
    mood: 'concerned',
    title: 'Thương cơ thể mình nhất nha! 🤗',
    dialogue: 'Giảm cân hay ăn kiêng đều cần an toàn và bền vững nha bạn ơi. Sức khỏe và nụ cười rạng rỡ của bạn mới là quan trọng nhất đó!',
    primaryAction: 'dismiss',
    ctaLabel: 'Xem lại',
    priority: 7,
    shouldBubble: true,
  }),
  companion_rest: entry('companion_rest', {
    domain: 'companion',
    mood: 'idle',
    title: 'Cứ từ từ, có tớ ở đây! ☕',
    dialogue: 'Không cần phải ép bản thân quá hoàn hảo hay áp lực đâu nè. Tụi mình cứ thong thả ghi chép và tiến bộ từng chút mỗi ngày nhé!',
    primaryAction: 'dismiss',
    ctaLabel: 'Đã hiểu',
    priority: 2,
    shouldBubble: false,
  }),
  companion_love: entry('companion_love', {
    domain: 'companion',
    mood: 'happy',
    title: 'Ăn ngon miệng cho đời vui tươi! 🍕',
    dialogue: 'Lối sống lành mạnh vẫn có chỗ cho những món ăn bạn cực kỳ yêu thích mà. Hãy thưởng thức thật ngon miệng và vui vẻ nha!',
    primaryAction: 'addMeal',
    ctaLabel: 'Ghi món',
    priority: 3,
    shouldBubble: false,
  }),
  companion_determined: entry('companion_determined', {
    domain: 'companion',
    mood: 'celebrating',
    title: 'Cố lên một xíu mỗi ngày nha! 💪',
    dialogue: 'Mỗi ngày tụi mình cố gắng một chút xíu thôi cũng tạo nên sự thay đổi kỳ diệu rồi. Tớ luôn tin tưởng bạn làm được mà!',
    primaryAction: 'addMeal',
    ctaLabel: 'Làm bước nhỏ',
    priority: 3,
    shouldBubble: false,
  }),
  companion_surprised: entry('companion_surprised', {
    domain: 'companion',
    mood: 'confused',
    title: 'A, điều bất ngờ gì đây ta? 🎁',
    dialogue: 'Ui, thông tin này nghe lạ lẫm và thú vị ghê nha! Để tớ tìm hiểu thật kỹ lưỡng lại chứ không dám đoán bừa đâu nè.',
    primaryAction: 'dismiss',
    ctaLabel: 'Kiểm tra',
    priority: 5,
    shouldBubble: false,
  }),
  companion_embarrassed: entry('companion_embarrassed', {
    domain: 'companion',
    mood: 'confused',
    title: 'Không sao đâu mà, đừng buồn nha! 🎈',
    dialogue: 'Lỡ quên ghi chép một hôm thì cũng không sao hết nè. Bạn đừng lo lắng nha, tụi mình cứ tiếp tục vui vẻ từ bữa ăn hôm nay thôi!',
    primaryAction: 'addMeal',
    ctaLabel: 'Ghi bữa gần nhất',
    priority: 4,
    shouldBubble: false,
  }),
  companion_strained: entry('companion_strained', {
    domain: 'system',
    mood: 'error',
    title: 'Tớ đang xoay mòng mòng xíu... 🌀',
    dialogue: 'Hệ thống đang hoạt động hết công suất nên tớ hơi chóng mặt một tẹo. Bạn kiên nhẫn chờ tớ quay lại một xíu nha!',
    primaryAction: 'dismiss',
    ctaLabel: 'Thử lại',
    priority: 6,
    shouldBubble: true,
  }),
  companion_box_idle: entry('companion_box_idle', {
    domain: 'companion',
    mood: 'idle',
    title: 'Tớ luôn ở bên bạn nè! 🤗',
    dialogue: 'Tớ vẫn luôn túc trực ở góc nhỏ này để đồng hành cùng bạn đó nha! Cần giúp đỡ gì thì cứ gọi tớ liền nhé!',
    primaryAction: 'scanFood',
    ctaLabel: 'Mở trợ lý',
    priority: 2,
    shouldBubble: false,
  }),
  app_offline: entry('app_offline', {
    domain: 'system',
    mood: 'error',
    title: 'Ơ kìa, sóng biến đi đâu mất tiêu... 🍂',
    dialogue: 'Sóng điện thoại hình như đang đi trốn mất rồi nè. Bạn cứ ăn uống ngon miệng, lát nữa mạng khỏe tụi mình ghi chép sau nha!',
    primaryAction: 'dismiss',
    ctaLabel: 'Thử lại',
    priority: 8,
    shouldBubble: true,
  }),
  generic_error: entry('generic_error', {
    domain: 'system',
    mood: 'error',
    title: 'Úi, có chút bối rối rồi! 👾',
    dialogue: 'Hình như hệ thống vừa gặp chút bối rối nhẹ rồi. Bạn thử lại hoặc quay lại trò chuyện với tớ sau một tẹo nha!',
    primaryAction: 'dismiss',
    ctaLabel: 'Thử lại',
    priority: 9,
    shouldBubble: true,
  }),
  water_added: entry('water_added', {
    domain: 'health',
    mood: 'thirsty',
    title: 'Đã tưới nước cho cơ thể rồi! 🌻',
    dialogue: 'Tuyệt vời quá đi! Mỗi ngụm nước mát lành đều đang giúp cơ thể bạn thanh lọc và tươi tắn lên trông thấy đó!',
    primaryAction: 'water',
    ctaLabel: 'Thêm tiếp',
    priority: 5,
    shouldBubble: true,
  }),
  streak_unlocked: entry('streak_unlocked', {
    domain: 'progress',
    mood: 'celebrating',
    title: 'Chuỗi ngày kiên trì lấp lánh! ✨',
    dialogue: 'Chuỗi ngày kiên trì của bạn đang tăng lên vùn vụt kìa! Siêu lòng tự hào luôn, tụi mình cùng giữ vững tinh thần nha!',
    primaryAction: 'viewProgress',
    ctaLabel: 'Xem thành tích',
    priority: 6,
    shouldBubble: true,
  }),
  calorie_caution: entry('calorie_caution', {
    domain: 'health',
    mood: 'concerned',
    title: 'Năng lượng tràn trề luôn nè! ⚡',
    dialogue: 'Bữa ăn này nạp năng lượng hơi dồi dào một xíu rồi nè. Không sao đâu nha, bữa sau tụi mình ăn thanh đạm hơn là cân bằng thôi mà!',
    primaryAction: 'addMeal',
    ctaLabel: 'Ghi tiếp',
    priority: 7,
    shouldBubble: true,
  }),
  report_ready: entry('report_ready', {
    domain: 'progress',
    mood: 'reporting',
    title: 'Món quà sức khỏe của bạn đây! 🎁',
    dialogue: 'Bản tin sức khỏe của bạn đã được tớ chuẩn bị sẵn sàng rồi nè! Cùng xem tuần qua tụi mình đã tiến bộ thế nào nha.',
    primaryAction: 'viewProgress',
    ctaLabel: 'Xem báo cáo',
    priority: 4,
    shouldBubble: true,
  }),
  pose_angry: roleEntry('pose_angry', 'angry', {
    domain: 'system',
    mood: 'concerned',
    title: 'Cảnh báo rõ ràng',
    dialogue: 'Dành cho trạng thái cần ngắt thao tác nguy hiểm và nhắc người dùng kiểm tra lại.',
    primaryAction: 'dismiss',
    priority: 1,
    shouldBubble: false,
  }),
  pose_sad_cry: roleEntry('pose_sad_cry', 'sadCry', {
    domain: 'system',
    mood: 'error',
    title: 'Lỗi cần xin lỗi',
    dialogue: 'Dành cho lỗi xử lý làm người dùng phải thử lại, với giọng mềm thay vì gây hoảng.',
    primaryAction: 'dismiss',
    priority: 1,
    shouldBubble: false,
  }),
  pose_confused: roleEntry('pose_confused', 'confused', {
    domain: 'scan',
    mood: 'confused',
    title: 'Chưa chắc kết quả',
    dialogue: 'Dành cho tình huống MoChi cần hỏi lại trước khi đưa ra gợi ý dinh dưỡng.',
    primaryAction: 'scanFood',
    priority: 1,
    shouldBubble: false,
  }),
  pose_calm: roleEntry('pose_calm', 'calm', {
    domain: 'companion',
    mood: 'idle',
    title: 'Nghỉ nhẹ',
    dialogue: 'Dành cho khoảnh khắc không có việc gấp nhưng vẫn muốn MoChi hiện diện dịu mắt.',
    primaryAction: 'dismiss',
    priority: 1,
    shouldBubble: false,
  }),
  pose_analyzing: roleEntry('pose_analyzing', 'analyzing', {
    domain: 'scan',
    mood: 'thinking',
    title: 'Đang xử lý nền',
    dialogue: 'Dành cho trạng thái phân tích cũ khi cần giữ tương thích với sprite hiện có.',
    primaryAction: 'scanFood',
    priority: 1,
    shouldBubble: false,
  }),
  pose_hydrate: roleEntry('pose_hydrate', 'hydrate', {
    domain: 'health',
    mood: 'thirsty',
    title: 'Nhắc nước gọn',
    dialogue: 'Dành cho lời nhắc uống nước dạng nhỏ, không chiếm nhiều không gian màn hình.',
    primaryAction: 'water',
    priority: 1,
    shouldBubble: false,
  }),
  pose_face_surprised: roleEntry('pose_face_surprised', 'faceSurprised', {
    domain: 'voice',
    mood: 'thinking',
    title: 'Nghe thấy tín hiệu',
    dialogue: 'Dành cho phản hồi nhanh khi người dùng vừa bắt đầu nói hoặc đưa dữ liệu mới.',
    primaryAction: 'dismiss',
    priority: 1,
    shouldBubble: false,
  }),
  pose_face_sad: roleEntry('pose_face_sad', 'faceSad', {
    domain: 'companion',
    mood: 'error',
    title: 'Tiếc nhẹ',
    dialogue: 'Dành cho trạng thái lỗi nhỏ khi MoChi cần nhận lỗi mà không làm nặng trải nghiệm.',
    primaryAction: 'dismiss',
    priority: 1,
    shouldBubble: false,
  }),
  pose_face_tired: roleEntry('pose_face_tired', 'faceTired', {
    domain: 'system',
    mood: 'concerned',
    title: 'Mạng chưa ổn',
    dialogue: 'Dành cho trạng thái chờ mạng hoặc tác vụ chậm cần thông báo một cách bình tĩnh.',
    primaryAction: 'dismiss',
    priority: 1,
    shouldBubble: false,
  }),
  pose_face_thinking: roleEntry('pose_face_thinking', 'faceThinking', {
    domain: 'logging',
    mood: 'thinking',
    title: 'Đang cân nhắc',
    dialogue: 'Dành cho bước cần người dùng xác nhận khẩu phần, món ăn hoặc lựa chọn tiếp theo.',
    primaryAction: 'addMeal',
    priority: 1,
    shouldBubble: false,
  }),
  pose_face_calm: roleEntry('pose_face_calm', 'faceCalm', {
    domain: 'companion',
    mood: 'idle',
    title: 'Bình tĩnh',
    dialogue: 'Dành cho các màn hình cần sự yên tâm, ít chuyển động và ít tạo áp lực.',
    primaryAction: 'dismiss',
    priority: 1,
    shouldBubble: false,
  }),
  pose_food_scale: roleEntry('pose_food_scale', 'foodScale', {
    domain: 'health',
    mood: 'thinking',
    title: 'Cân bằng dinh dưỡng',
    dialogue: 'Dành cho phần giải thích mục tiêu dinh dưỡng hoặc điều chỉnh khẩu phần.',
    primaryAction: 'addMeal',
    priority: 1,
    shouldBubble: false,
  }),
  pose_cake_concern: roleEntry('pose_cake_concern', 'cakeConcern', {
    domain: 'health',
    mood: 'concerned',
    title: 'Cẩn thận calo',
    dialogue: 'Dành cho lời nhắc nhẹ khi bữa ăn có thể lệch khỏi mục tiêu trong ngày.',
    primaryAction: 'addMeal',
    priority: 1,
    shouldBubble: false,
  }),
  pose_tablet_meal: roleEntry('pose_tablet_meal', 'tabletMeal', {
    domain: 'logging',
    mood: 'hungry',
    title: 'Xem lại bữa',
    dialogue: 'Dành cho màn hình rà soát nhật ký hoặc chỉnh lại thông tin bữa ăn đã ghi.',
    primaryAction: 'viewDiary',
    priority: 1,
    shouldBubble: false,
  }),
  pose_carb_explain: roleEntry('pose_carb_explain', 'carbExplain', {
    domain: 'health',
    mood: 'thinking',
    title: 'Giải thích macro',
    dialogue: 'Dành cho phần hướng dẫn protein, carb và fat bằng ngôn ngữ dễ hiểu.',
    primaryAction: 'dismiss',
    priority: 1,
    shouldBubble: false,
  }),
  pose_spin_choice: roleEntry('pose_spin_choice', 'spinChoice', {
    domain: 'logging',
    mood: 'thinking',
    title: 'Chọn nhanh',
    dialogue: 'Dành cho trạng thái gợi ý nhiều lựa chọn khi người dùng chưa biết ghi món nào.',
    primaryAction: 'addMeal',
    priority: 1,
    shouldBubble: false,
  }),
  pose_logout_notice: roleEntry('pose_logout_notice', 'logoutNotice', {
    domain: 'profile',
    mood: 'idle',
    title: 'Xác nhận tài khoản',
    dialogue: 'Dành cho thao tác đăng xuất hoặc đổi thiết lập tài khoản cần xác nhận rõ ràng.',
    primaryAction: 'dismiss',
    priority: 1,
    shouldBubble: false,
  }),
  pose_scan_success_face: roleEntry('pose_scan_success_face', 'scanSuccessFace', {
    domain: 'scan',
    mood: 'happy',
    title: 'Scan ổn',
    dialogue: 'Dành cho phản hồi nhỏ khi kết quả scan đủ tốt và người dùng chỉ cần kiểm tra lại.',
    primaryAction: 'addMeal',
    priority: 1,
    shouldBubble: false,
  }),
  pose_scan_uncertain_face: roleEntry('pose_scan_uncertain_face', 'scanUncertainFace', {
    domain: 'scan',
    mood: 'confused',
    title: 'Scan chưa chắc',
    dialogue: 'Dành cho phản hồi nhỏ khi MoChi cần người dùng xác nhận món hoặc khẩu phần.',
    primaryAction: 'scanFood',
    priority: 1,
    shouldBubble: false,
  }),
  pose_secure_face: roleEntry('pose_secure_face', 'secureFace', {
    domain: 'profile',
    mood: 'concerned',
    title: 'Bảo mật nhẹ',
    dialogue: 'Dành cho thông báo tài khoản cần sự cẩn trọng nhưng không làm người dùng lo lắng.',
    primaryAction: 'dismiss',
    priority: 1,
    shouldBubble: false,
  }),
};

export const MOCHI_CONTEXT_EVENT_TO_POSE: Record<MoChiPetEventType, MoChiPoseKey> =
  MOCHI_EVENT_TO_POSE;

export const getMoChiExperience = (eventType: MoChiPetEventType): MoChiExperienceEntry =>
  MOCHI_EXPERIENCE_CATALOG[eventType] ?? MOCHI_EXPERIENCE_CATALOG.app_idle;
