const RECIPE_INGREDIENT_ELIGIBLE_LABELS = new Set([
  'bun',
  'banh_trang',
  'rice',
  'noodles',
  'chicken',
  'beef',
  'pork',
  'pork_belly',
  'pork_rib',
  'fish',
  'shrimp',
  'crab',
  'squid',
  'egg',
  'tofu',
  'tempeh',
  'tomato',
  'cucumber',
  'carrot',
  'potato',
  'sweet_potato',
  'spinach',
  'water_spinach',
  'bokchoy',
  'cabbage',
  'cauliflower',
  'broccoli',
  'eggplant',
  'bitter_gourd',
  'bottle_gourd',
  'pumpkin',
  'radish',
  'long_beans',
  'beans',
  'peas',
  'mushroom',
  'chayote',
  'corn',
  'onion',
  'shallot',
  'green_onion',
  'garlic',
  'chili',
  'ginger',
  'galangal',
  'lemongrass',
  'leek',
  'lime_leaf',
  'coriander_seed',
  'fennel_seed',
  'star_anise',
  'cinnamon',
  'clove',
  'turmeric',
  'bell_pepper',
  'lime',
]);

const FINISHED_DISH_LABELS = new Set([
  'banh_mi',
  'pho',
  'bot_chien',
  'goi_cuon',
  'fried_rice',
  'com_tam',
  'thit_kho',
  'ca_kho',
  'canh',
  'banh_beo',
  'banh_bo',
  'banh_bot_loc',
  'banh_can',
  'banh_canh',
  'banh_chung',
  'banh_cong',
  'banh_cuon',
  'banh_da_lon',
  'banh_duc',
  'banh_khot',
  'banh_tet',
  'banh_xeo',
  'banh_trang_tron',
  'bo_kho',
  'bo_la_lot',
  'bun_bo_hue',
  'bun_cha',
  'bun_dau',
  'bun_mam',
  'bun_rieu',
  'cha_gio',
  'hu_tieu',
  'lau',
  'mi_quang',
  'cao_lau',
  'xoi',
  'chao_long',
  'sup_cua',
  'bitter_melon_soup',
  'caramelized_fish_clay_pot',
  'chicken_rice',
  'pumpkin_soup',
  'purple_yam_soup',
  'steamed_pork_belly_taro',
  'sizzling_beef_steak',
  'hollow_fried_sesame_donut',
  'nuoc_cham',
  'grilled_pork_belly',
  'fried_egg',
]);

const normalizeLabel = (value: string | null | undefined): string =>
  (value ?? '').trim().toLowerCase();

export const isRecipeIngredientEligibleLabel = (
  label: string | null | undefined,
): boolean => RECIPE_INGREDIENT_ELIGIBLE_LABELS.has(normalizeLabel(label));

export const isFinishedDishLabel = (label: string | null | undefined): boolean =>
  FINISHED_DISH_LABELS.has(normalizeLabel(label));
