using EatFitAI.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;

namespace EatFitAI.API.Services;

public sealed class ProductSchemaBootstrapper
{
    private static readonly SemaphoreSlim SchemaInitLock = new(1, 1);
    private static bool _schemaInitialized;

    private readonly ApplicationDbContext _context;
    private readonly IConfiguration _configuration;
    private readonly IHostEnvironment _environment;
    private readonly ILogger<ProductSchemaBootstrapper> _logger;

    public ProductSchemaBootstrapper(
        ApplicationDbContext context,
        IConfiguration configuration,
        IHostEnvironment environment,
        ILogger<ProductSchemaBootstrapper> logger)
    {
        _context = context;
        _configuration = configuration;
        _environment = environment;
        _logger = logger;
    }

    public static string SchemaSql => """
        ALTER TABLE IF EXISTS "FoodItem"
            ADD COLUMN IF NOT EXISTS "Barcode" varchar(64) NULL;

        CREATE INDEX IF NOT EXISTS "IX_FoodItem_Barcode_Active"
            ON "FoodItem" ("Barcode")
            WHERE "Barcode" IS NOT NULL AND "IsDeleted" = false AND "IsActive" = true;

        ALTER TABLE IF EXISTS "MealDiary"
            ADD COLUMN IF NOT EXISTS "InputMethod" varchar(30) NULL,
            ADD COLUMN IF NOT EXISTS "IsRoughLog" boolean NOT NULL DEFAULT false,
            ADD COLUMN IF NOT EXISTS "UserConfirmed" boolean NOT NULL DEFAULT true,
            ADD COLUMN IF NOT EXISTS "ConfidenceScore" numeric(5,4) NULL,
            ADD COLUMN IF NOT EXISTS "TrustSource" varchar(50) NULL,
            ADD COLUMN IF NOT EXISTS "DiaryMissingNutrients" varchar(200) NULL;

        CREATE TABLE IF NOT EXISTS "MealDayMarker" (
            "MealDayMarkerId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "UserId" uuid NOT NULL REFERENCES "Users" ("UserId"),
            "LocalDate" date NOT NULL,
            "MealTypeId" integer NULL REFERENCES "MealType" ("MealTypeId"),
            "MarkerType" varchar(40) NOT NULL,
            "Reason" varchar(200) NULL,
            "CreatedAt" timestamp(3) with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
            "UpdatedAt" timestamp(3) with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
            "IsDeleted" boolean NOT NULL DEFAULT false
        );

        CREATE INDEX IF NOT EXISTS "IX_MealDayMarker_UserDate"
            ON "MealDayMarker" ("UserId", "LocalDate")
            WHERE "IsDeleted" = false;

        CREATE INDEX IF NOT EXISTS "IX_MealDayMarker_UserDateMealType"
            ON "MealDayMarker" ("UserId", "LocalDate", "MealTypeId", "MarkerType")
            WHERE "IsDeleted" = false;

        CREATE TABLE IF NOT EXISTS "WeeklyReviewAction" (
            "WeeklyReviewActionId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "UserId" uuid NOT NULL REFERENCES "Users" ("UserId"),
            "WeekStartDate" date NOT NULL,
            "ActionKey" varchar(80) NOT NULL,
            "Label" varchar(200) NOT NULL,
            "Status" varchar(30) NOT NULL DEFAULT 'suggested',
            "ReplacementText" varchar(200) NULL,
            "CreatedAt" timestamp(3) with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
            "UpdatedAt" timestamp(3) with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
        );

        CREATE UNIQUE INDEX IF NOT EXISTS "UQ_WeeklyReviewAction_UserWeekAction"
            ON "WeeklyReviewAction" ("UserId", "WeekStartDate", "ActionKey");

        CREATE TABLE IF NOT EXISTS "TelemetryEvent" (
            "TelemetryEventId" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
            "UserId" uuid NULL REFERENCES "Users" ("UserId") ON DELETE SET NULL,
            "Name" varchar(120) NOT NULL,
            "Category" varchar(60) NOT NULL,
            "OccurredAt" timestamp without time zone NOT NULL,
            "Screen" varchar(120) NULL,
            "Flow" varchar(120) NULL,
            "Step" varchar(120) NULL,
            "Status" varchar(60) NULL,
            "SessionId" varchar(120) NULL,
            "MetadataJson" text NULL,
            "RequestId" varchar(120) NULL,
            "CreatedAt" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
        );

        CREATE INDEX IF NOT EXISTS "IX_TelemetryEvent_OccurredAt"
            ON "TelemetryEvent" ("OccurredAt");

        CREATE INDEX IF NOT EXISTS "IX_TelemetryEvent_UserId_OccurredAt"
            ON "TelemetryEvent" ("UserId", "OccurredAt");

        CREATE INDEX IF NOT EXISTS "IX_TelemetryEvent_Category_OccurredAt"
            ON "TelemetryEvent" ("Category", "OccurredAt");

        CREATE TABLE IF NOT EXISTS "SubscriptionPlan" (
            "PlanCode" varchar(40) PRIMARY KEY,
            "DisplayName" varchar(120) NOT NULL,
            "IsPremium" boolean NOT NULL DEFAULT false,
            "FeaturesJson" text NOT NULL DEFAULT '{{}}',
            "LimitsJson" text NOT NULL DEFAULT '{{}}',
            "IsActive" boolean NOT NULL DEFAULT true,
            "SortOrder" integer NOT NULL DEFAULT 0,
            "CreatedAt" timestamp(3) with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
            "UpdatedAt" timestamp(3) with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
        );

        CREATE TABLE IF NOT EXISTS "UserEntitlement" (
            "UserEntitlementId" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
            "UserId" uuid NOT NULL REFERENCES "Users" ("UserId") ON DELETE CASCADE,
            "PlanCode" varchar(40) NOT NULL REFERENCES "SubscriptionPlan" ("PlanCode") ON DELETE RESTRICT,
            "Status" varchar(40) NOT NULL DEFAULT 'active',
            "Source" varchar(60) NOT NULL DEFAULT 'manual',
            "StartsAt" timestamp(3) with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
            "ExpiresAt" timestamp with time zone NULL,
            "CreatedAt" timestamp(3) with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
            "UpdatedAt" timestamp(3) with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
        );

        CREATE INDEX IF NOT EXISTS "IX_UserEntitlement_User_Status_Expires"
            ON "UserEntitlement" ("UserId", "Status", "ExpiresAt");

        INSERT INTO "SubscriptionPlan" ("PlanCode", "DisplayName", "IsPremium", "FeaturesJson", "LimitsJson", "IsActive", "SortOrder")
        VALUES
            ('free', 'EatFitAI Free', false, '{{"basicLogging":true,"aiScan":true,"mochiCoach":true}}', '{{"aiScansPerDay":-1,"aiFeatureUsesPerDay":20,"recipeSuggestionsPerDay":20}}', true, 0),
            ('premium', 'EatFitAI Premium', true, '{{"basicLogging":true,"aiScan":true,"mochiCoach":true,"advancedInsights":true,"priorityAi":true}}', '{{"aiScansPerDay":-1,"aiFeatureUsesPerDay":-1,"recipeSuggestionsPerDay":-1}}', true, 10)
        ON CONFLICT ("PlanCode") DO UPDATE
        SET "DisplayName" = EXCLUDED."DisplayName",
            "IsPremium" = EXCLUDED."IsPremium",
            "FeaturesJson" = EXCLUDED."FeaturesJson",
            "LimitsJson" = EXCLUDED."LimitsJson",
            "IsActive" = EXCLUDED."IsActive",
            "SortOrder" = EXCLUDED."SortOrder",
            "UpdatedAt" = NOW() AT TIME ZONE 'UTC';

        DO $$
        BEGIN
            IF to_regclass('public."WaterIntake"') IS NOT NULL THEN
                EXECUTE 'ALTER TABLE "WaterIntake" ENABLE ROW LEVEL SECURITY';
                EXECUTE 'REVOKE ALL ON TABLE "WaterIntake" FROM anon, authenticated';
                EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "WaterIntake" TO authenticated';

                IF to_regclass('public."WaterIntake_WaterIntakeId_seq"') IS NOT NULL THEN
                    EXECUTE 'REVOKE ALL ON SEQUENCE "WaterIntake_WaterIntakeId_seq" FROM anon, authenticated';
                    EXECUTE 'GRANT USAGE, SELECT ON SEQUENCE "WaterIntake_WaterIntakeId_seq" TO authenticated';
                END IF;

                EXECUTE 'DROP POLICY IF EXISTS "WaterIntake_authenticated_own_read" ON "WaterIntake"';
                EXECUTE 'CREATE POLICY "WaterIntake_authenticated_own_read"
                    ON "WaterIntake"
                    FOR SELECT
                    TO authenticated
                    USING ((select auth.uid()) IS NOT NULL AND (select auth.uid()) = "UserId")';

                EXECUTE 'DROP POLICY IF EXISTS "WaterIntake_authenticated_own_insert" ON "WaterIntake"';
                EXECUTE 'CREATE POLICY "WaterIntake_authenticated_own_insert"
                    ON "WaterIntake"
                    FOR INSERT
                    TO authenticated
                    WITH CHECK ((select auth.uid()) IS NOT NULL AND (select auth.uid()) = "UserId")';

                EXECUTE 'DROP POLICY IF EXISTS "WaterIntake_authenticated_own_update" ON "WaterIntake"';
                EXECUTE 'CREATE POLICY "WaterIntake_authenticated_own_update"
                    ON "WaterIntake"
                    FOR UPDATE
                    TO authenticated
                    USING ((select auth.uid()) IS NOT NULL AND (select auth.uid()) = "UserId")
                    WITH CHECK ((select auth.uid()) IS NOT NULL AND (select auth.uid()) = "UserId")';

                EXECUTE 'DROP POLICY IF EXISTS "WaterIntake_authenticated_own_delete" ON "WaterIntake"';
                EXECUTE 'CREATE POLICY "WaterIntake_authenticated_own_delete"
                    ON "WaterIntake"
                    FOR DELETE
                    TO authenticated
                    USING ((select auth.uid()) IS NOT NULL AND (select auth.uid()) = "UserId")';
            END IF;

            IF to_regclass('public."TelemetryEvent"') IS NOT NULL THEN
                EXECUTE 'ALTER TABLE "TelemetryEvent" ENABLE ROW LEVEL SECURITY';
                EXECUTE 'REVOKE ALL ON TABLE "TelemetryEvent" FROM anon, authenticated';
                EXECUTE 'GRANT INSERT ON TABLE "TelemetryEvent" TO authenticated';

                EXECUTE 'DROP POLICY IF EXISTS "TelemetryEvent_authenticated_own_insert" ON "TelemetryEvent"';
                EXECUTE 'CREATE POLICY "TelemetryEvent_authenticated_own_insert"
                    ON "TelemetryEvent"
                    FOR INSERT
                    TO authenticated
                    WITH CHECK ((select auth.uid()) IS NOT NULL AND (select auth.uid()) = "UserId")';
            END IF;

            IF to_regclass('public."MealDayMarker"') IS NOT NULL THEN
                EXECUTE 'ALTER TABLE "MealDayMarker" ENABLE ROW LEVEL SECURITY';
                EXECUTE 'REVOKE ALL ON TABLE "MealDayMarker" FROM anon, authenticated';
            END IF;

            IF to_regclass('public."WeeklyReviewAction"') IS NOT NULL THEN
                EXECUTE 'ALTER TABLE "WeeklyReviewAction" ENABLE ROW LEVEL SECURITY';
                EXECUTE 'REVOKE ALL ON TABLE "WeeklyReviewAction" FROM anon, authenticated';
            END IF;

            IF to_regclass('public."SubscriptionPlan"') IS NOT NULL THEN
                EXECUTE 'ALTER TABLE "SubscriptionPlan" ENABLE ROW LEVEL SECURITY';
                EXECUTE 'REVOKE ALL ON TABLE "SubscriptionPlan" FROM anon, authenticated';
            END IF;

            IF to_regclass('public."UserEntitlement"') IS NOT NULL THEN
                EXECUTE 'ALTER TABLE "UserEntitlement" ENABLE ROW LEVEL SECURITY';
                EXECUTE 'REVOKE ALL ON TABLE "UserEntitlement" FROM anon, authenticated';
            END IF;

            IF to_regclass('public."GeminiProviderState"') IS NOT NULL THEN
                EXECUTE 'ALTER TABLE "GeminiProviderState" ENABLE ROW LEVEL SECURITY';
                EXECUTE 'REVOKE ALL ON TABLE "GeminiProviderState" FROM anon, authenticated';
            END IF;

            IF to_regclass('public."__EFMigrationsHistory"') IS NOT NULL THEN
                EXECUTE 'ALTER TABLE "__EFMigrationsHistory" ENABLE ROW LEVEL SECURITY';
                EXECUTE 'REVOKE ALL ON TABLE "__EFMigrationsHistory" FROM anon, authenticated';
            END IF;
        END $$;

        NOTIFY pgrst, 'reload schema';
        """;

    public async Task EnsureSchemaAsync(CancellationToken cancellationToken = default, bool force = false)
    {
        if (_schemaInitialized || !_context.Database.IsRelational())
        {
            return;
        }

        if (!SchemaBootstrapStartupGate.ShouldAllowRuntimeRepair(_configuration, _environment, force))
        {
            return;
        }

        await SchemaInitLock.WaitAsync(cancellationToken);
        try
        {
            if (_schemaInitialized || !_context.Database.IsRelational())
            {
                return;
            }

            if (!SchemaBootstrapStartupGate.ShouldAllowRuntimeRepair(_configuration, _environment, force))
            {
                return;
            }

            await _context.Database.ExecuteSqlRawAsync(
                SchemaSql,
                parameters: Array.Empty<object>(),
                cancellationToken: cancellationToken);
            _schemaInitialized = true;
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Unable to ensure product schema drift repair.");
            throw;
        }
        finally
        {
            SchemaInitLock.Release();
        }
    }
}
