// <auto-generated />
using System;
using EatFitAI.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EatFitAI.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251102081352_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EatFitAI.API.Models.AILog", b =>
                {
                    b.Property<int>("AILogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AILogId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AILogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("int")
                        .HasColumnName("DurationMs");

                    b.Property<string>("InputJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("InputJson");

                    b.Property<string>("OutputJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OutputJson");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("AILogId");

                    b.HasIndex("UserId");

                    b.ToTable("AILog");
                });

            modelBuilder.Entity("EatFitAI.API.Models.AISuggestion", b =>
                {
                    b.Property<int>("AISuggestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AISuggestionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AISuggestionId"));

                    b.Property<int>("AILogId")
                        .HasColumnType("int")
                        .HasColumnName("AILogId");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("Confidence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int")
                        .HasColumnName("FoodItemId");

                    b.HasKey("AISuggestionId");

                    b.HasIndex("AILogId");

                    b.HasIndex("FoodItemId");

                    b.ToTable("AISuggestion", t =>
                        {
                            t.HasCheckConstraint("CK_AISuggestion_Conf", "Confidence >= 0 AND Confidence <= 1");
                        });
                });

            modelBuilder.Entity("EatFitAI.API.Models.ActivityLevel", b =>
                {
                    b.Property<int>("ActivityLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ActivityLevelId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityLevelId"));

                    b.Property<decimal>("ActivityFactor")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("ActivityFactor");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("ActivityLevelId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ActivityLevel", t =>
                        {
                            t.HasCheckConstraint("CK_ActivityLevel_Positive", "ActivityFactor > 0");
                        });
                });

            modelBuilder.Entity("EatFitAI.API.Models.BodyMetric", b =>
                {
                    b.Property<int>("BodyMetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BodyMetricId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BodyMetricId"));

                    b.Property<decimal?>("BodyFatPct")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("BodyFatPct");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("HeightCm");

                    b.Property<DateTime>("MeasuredDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MeasuredDate");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Note");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("WeightKg");

                    b.HasKey("BodyMetricId");

                    b.HasIndex("UserId");

                    b.ToTable("BodyMetric");
                });

            modelBuilder.Entity("EatFitAI.API.Models.FoodItem", b =>
                {
                    b.Property<int>("FoodItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FoodItemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodItemId"));

                    b.Property<decimal>("CaloriesPer100g")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("CaloriesPer100g");

                    b.Property<decimal>("CarbPer100g")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("CarbPer100g");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<decimal>("FatPer100g")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("FatPer100g");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FoodName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<decimal>("ProteinPer100g")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("ProteinPer100g");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("FoodItemId");

                    b.ToTable("FoodItem", t =>
                        {
                            t.HasCheckConstraint("CK_FI_C_NonNeg", "CarbPer100g >= 0");

                            t.HasCheckConstraint("CK_FI_Cal_NonNeg", "CaloriesPer100g >= 0");

                            t.HasCheckConstraint("CK_FI_F_NonNeg", "FatPer100g >= 0");

                            t.HasCheckConstraint("CK_FI_P_NonNeg", "ProteinPer100g >= 0");
                        });
                });

            modelBuilder.Entity("EatFitAI.API.Models.FoodServing", b =>
                {
                    b.Property<int>("FoodServingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FoodServingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodServingId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Description");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int")
                        .HasColumnName("FoodItemId");

                    b.Property<decimal>("GramsPerUnit")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("GramsPerUnit");

                    b.Property<int>("ServingUnitId")
                        .HasColumnType("int")
                        .HasColumnName("ServingUnitId");

                    b.HasKey("FoodServingId");

                    b.HasIndex("ServingUnitId");

                    b.HasIndex("FoodItemId", "ServingUnitId")
                        .IsUnique();

                    b.ToTable("FoodServing", t =>
                        {
                            t.HasCheckConstraint("CK_FoodServing_Positive", "GramsPerUnit > 0");
                        });
                });

            modelBuilder.Entity("EatFitAI.API.Models.ImageDetection", b =>
                {
                    b.Property<int>("ImageDetectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ImageDetectionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageDetectionId"));

                    b.Property<int>("AILogId")
                        .HasColumnType("int")
                        .HasColumnName("AILogId");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("Confidence");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Label");

                    b.HasKey("ImageDetectionId");

                    b.HasIndex("AILogId");

                    b.ToTable("ImageDetection", t =>
                        {
                            t.HasCheckConstraint("CK_ImageDetection_Conf", "Confidence >= 0 AND Confidence <= 1");
                        });
                });

            modelBuilder.Entity("EatFitAI.API.Models.MealDiary", b =>
                {
                    b.Property<int>("MealDiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MealDiaryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealDiaryId"));

                    b.Property<decimal>("Calories")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Calories");

                    b.Property<decimal>("Carb")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Carb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("EatenDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EatenDate");

                    b.Property<decimal>("Fat")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Fat");

                    b.Property<int?>("FoodItemId")
                        .HasColumnType("int")
                        .HasColumnName("FoodItemId");

                    b.Property<decimal>("Grams")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Grams");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int>("MealTypeId")
                        .HasColumnType("int")
                        .HasColumnName("MealTypeId");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Note");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PhotoUrl");

                    b.Property<decimal?>("PortionQuantity")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PortionQuantity");

                    b.Property<decimal>("Protein")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Protein");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("int")
                        .HasColumnName("RecipeId");

                    b.Property<int?>("ServingUnitId")
                        .HasColumnType("int")
                        .HasColumnName("ServingUnitId");

                    b.Property<string>("SourceMethod")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("SourceMethod");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<int?>("UserDishId")
                        .HasColumnType("int")
                        .HasColumnName("UserDishId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("MealDiaryId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("ServingUnitId");

                    b.HasIndex("UserDishId");

                    b.HasIndex("UserId");

                    b.ToTable("MealDiary", t =>
                        {
                            t.HasCheckConstraint("CK_MealDiary_C_NonNeg", "Carb >= 0");

                            t.HasCheckConstraint("CK_MealDiary_Cal_NonNeg", "Calories >= 0");

                            t.HasCheckConstraint("CK_MealDiary_F_NonNeg", "Fat >= 0");

                            t.HasCheckConstraint("CK_MealDiary_Grams_NonNeg", "Grams >= 0");

                            t.HasCheckConstraint("CK_MealDiary_P_NonNeg", "Protein >= 0");

                            t.HasCheckConstraint("CK_MealDiary_Portion_Positive", "PortionQuantity IS NULL OR PortionQuantity > 0");
                        });
                });

            modelBuilder.Entity("EatFitAI.API.Models.MealType", b =>
                {
                    b.Property<int>("MealTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MealTypeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("MealTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MealType");
                });

            modelBuilder.Entity("EatFitAI.API.Models.NutritionTarget", b =>
                {
                    b.Property<int>("NutritionTargetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NutritionTargetId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NutritionTargetId"));

                    b.Property<int?>("ActivityLevelId")
                        .HasColumnType("int")
                        .HasColumnName("ActivityLevelId");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2")
                        .HasColumnName("EffectiveFrom");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2")
                        .HasColumnName("EffectiveTo");

                    b.Property<int>("TargetCalories")
                        .HasColumnType("int")
                        .HasColumnName("TargetCalories");

                    b.Property<int>("TargetCarb")
                        .HasColumnType("int")
                        .HasColumnName("TargetCarb");

                    b.Property<int>("TargetFat")
                        .HasColumnType("int")
                        .HasColumnName("TargetFat");

                    b.Property<int>("TargetProtein")
                        .HasColumnType("int")
                        .HasColumnName("TargetProtein");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("NutritionTargetId");

                    b.HasIndex("ActivityLevelId");

                    b.HasIndex("UserId");

                    b.ToTable("NutritionTarget");
                });

            modelBuilder.Entity("EatFitAI.API.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RecipeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RecipeName");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("EatFitAI.API.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RecipeIngredientId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeIngredientId"));

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int")
                        .HasColumnName("FoodItemId");

                    b.Property<decimal>("Grams")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Grams");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int")
                        .HasColumnName("RecipeId");

                    b.HasKey("RecipeIngredientId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredient", t =>
                        {
                            t.HasCheckConstraint("CK_RecipeIngredient_Positive", "Grams >= 0");
                        });
                });

            modelBuilder.Entity("EatFitAI.API.Models.ServingUnit", b =>
                {
                    b.Property<int>("ServingUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServingUnitId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServingUnitId"));

                    b.Property<bool>("IsBaseUnit")
                        .HasColumnType("bit")
                        .HasColumnName("IsBaseUnit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Symbol");

                    b.HasKey("ServingUnitId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ServingUnit");
                });

            modelBuilder.Entity("EatFitAI.API.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("DisplayName");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Email");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("PasswordHash");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EatFitAI.API.Models.UserDish", b =>
                {
                    b.Property<int>("UserDishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserDishId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserDishId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DishName");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("UserDishId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDish");
                });

            modelBuilder.Entity("EatFitAI.API.Models.UserDishIngredient", b =>
                {
                    b.Property<int>("UserDishIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserDishIngredientId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserDishIngredientId"));

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int")
                        .HasColumnName("FoodItemId");

                    b.Property<decimal>("Grams")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Grams");

                    b.Property<int>("UserDishId")
                        .HasColumnType("int")
                        .HasColumnName("UserDishId");

                    b.HasKey("UserDishIngredientId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("UserDishId");

                    b.ToTable("UserDishIngredient", t =>
                        {
                            t.HasCheckConstraint("CK_UserDishIngredient_Positive", "Grams >= 0");
                        });
                });

            modelBuilder.Entity("EatFitAI.API.Models.UserFavoriteFood", b =>
                {
                    b.Property<int>("UserFavoriteFoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserFavoriteFoodId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserFavoriteFoodId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int")
                        .HasColumnName("FoodItemId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("UserFavoriteFoodId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("UserId", "FoodItemId")
                        .IsUnique();

                    b.ToTable("UserFavoriteFood");
                });

            modelBuilder.Entity("EatFitAI.API.Models.UserRecentFood", b =>
                {
                    b.Property<int>("UserRecentFoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserRecentFoodId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRecentFoodId"));

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int")
                        .HasColumnName("FoodItemId");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastUsedAt");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int")
                        .HasColumnName("UsedCount");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("UserRecentFoodId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("UserId", "FoodItemId")
                        .IsUnique();

                    b.ToTable("UserRecentFood");
                });

            modelBuilder.Entity("EatFitAI.API.Models.AILog", b =>
                {
                    b.HasOne("EatFitAI.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.API.Models.AISuggestion", b =>
                {
                    b.HasOne("EatFitAI.API.Models.AILog", "AILog")
                        .WithMany()
                        .HasForeignKey("AILogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatFitAI.API.Models.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AILog");

                    b.Navigation("FoodItem");
                });

            modelBuilder.Entity("EatFitAI.API.Models.BodyMetric", b =>
                {
                    b.HasOne("EatFitAI.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.API.Models.FoodServing", b =>
                {
                    b.HasOne("EatFitAI.API.Models.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatFitAI.API.Models.ServingUnit", "ServingUnit")
                        .WithMany()
                        .HasForeignKey("ServingUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("ServingUnit");
                });

            modelBuilder.Entity("EatFitAI.API.Models.ImageDetection", b =>
                {
                    b.HasOne("EatFitAI.API.Models.AILog", "AILog")
                        .WithMany()
                        .HasForeignKey("AILogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AILog");
                });

            modelBuilder.Entity("EatFitAI.API.Models.MealDiary", b =>
                {
                    b.HasOne("EatFitAI.API.Models.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId");

                    b.HasOne("EatFitAI.API.Models.MealType", "MealType")
                        .WithMany()
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatFitAI.API.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId");

                    b.HasOne("EatFitAI.API.Models.ServingUnit", "ServingUnit")
                        .WithMany()
                        .HasForeignKey("ServingUnitId");

                    b.HasOne("EatFitAI.API.Models.UserDish", "UserDish")
                        .WithMany()
                        .HasForeignKey("UserDishId");

                    b.HasOne("EatFitAI.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("MealType");

                    b.Navigation("Recipe");

                    b.Navigation("ServingUnit");

                    b.Navigation("User");

                    b.Navigation("UserDish");
                });

            modelBuilder.Entity("EatFitAI.API.Models.NutritionTarget", b =>
                {
                    b.HasOne("EatFitAI.API.Models.ActivityLevel", "ActivityLevel")
                        .WithMany()
                        .HasForeignKey("ActivityLevelId");

                    b.HasOne("EatFitAI.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityLevel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.API.Models.RecipeIngredient", b =>
                {
                    b.HasOne("EatFitAI.API.Models.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatFitAI.API.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("EatFitAI.API.Models.UserDish", b =>
                {
                    b.HasOne("EatFitAI.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.API.Models.UserDishIngredient", b =>
                {
                    b.HasOne("EatFitAI.API.Models.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatFitAI.API.Models.UserDish", "UserDish")
                        .WithMany()
                        .HasForeignKey("UserDishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("UserDish");
                });

            modelBuilder.Entity("EatFitAI.API.Models.UserFavoriteFood", b =>
                {
                    b.HasOne("EatFitAI.API.Models.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatFitAI.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.API.Models.UserRecentFood", b =>
                {
                    b.HasOne("EatFitAI.API.Models.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatFitAI.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
