// <auto-generated />
using System;
using EatFitAI.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EatFitAI.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260410175726_AddAdminRoleAndGeminiKeys")]
    partial class AddAdminRoleAndGeminiKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EatFitAI.API.Models.AILog", b =>
                {
                    b.Property<int>("AILogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AILogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("InputJson")
                        .HasColumnType("text");

                    b.Property<string>("OutputJson")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("AILogId");

                    b.HasIndex(new[] { "UserId", "Action", "CreatedAt" }, "IX_AILog_User_Action_CreatedAt");

                    b.ToTable("AILog", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.AISuggestion", b =>
                {
                    b.Property<int>("AISuggestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AISuggestionId"));

                    b.Property<int>("AILogId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("integer");

                    b.HasKey("AISuggestionId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex(new[] { "AILogId" }, "IX_AISuggestion_AILog");

                    b.ToTable("AISuggestion", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.ActivityLevel", b =>
                {
                    b.Property<int>("ActivityLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActivityLevelId"));

                    b.Property<decimal>("ActivityFactor")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ActivityLevelId");

                    b.HasIndex(new[] { "Name" }, "UQ_ActivityLevel_Name")
                        .IsUnique();

                    b.ToTable("ActivityLevel", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.AiCorrectionEvent", b =>
                {
                    b.Property<int>("AiCorrectionEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AiCorrectionEventId"));

                    b.Property<DateTime?>("ClientTimestamp")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<decimal?>("DetectedConfidence")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<int?>("FoodItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SelectedFoodName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("AiCorrectionEventId");

                    b.HasIndex(new[] { "Label", "CreatedAt" }, "IX_AiCorrectionEvent_Label_CreatedAt");

                    b.HasIndex(new[] { "Source", "CreatedAt" }, "IX_AiCorrectionEvent_Source_CreatedAt");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "IX_AiCorrectionEvent_User_CreatedAt");

                    b.ToTable("AiCorrectionEvent", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.AiLabelMap", b =>
                {
                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int?>("FoodItemId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinConfidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(0.60m);

                    b.HasKey("Label");

                    b.ToTable("AiLabelMap", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.BodyMetric", b =>
                {
                    b.Property<int>("BodyMetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BodyMetricId"));

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateOnly>("MeasuredDate")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("BodyMetricId");

                    b.HasIndex(new[] { "UserId", "MeasuredDate" }, "IX_BodyMetric_User_MeasuredDate");

                    b.ToTable("BodyMetric", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.FoodItem", b =>
                {
                    b.Property<int>("FoodItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FoodItemId"));

                    b.Property<decimal>("CaloriesPer100g")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("CarbPer100g")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<decimal>("FatPer100g")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FoodNameEn")
                        .HasColumnType("text");

                    b.Property<string>("FoodNameUnsigned")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ProteinPer100g")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ThumbNail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("FoodItemId");

                    b.HasIndex(new[] { "FoodName" }, "IX_FoodItem_Name")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("FoodItem", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.FoodServing", b =>
                {
                    b.Property<int>("FoodServingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FoodServingId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("integer");

                    b.Property<decimal>("GramsPerUnit")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ServingUnitId")
                        .HasColumnType("integer");

                    b.HasKey("FoodServingId");

                    b.HasIndex("ServingUnitId");

                    b.HasIndex(new[] { "FoodItemId", "ServingUnitId" }, "UQ_FoodServing")
                        .IsUnique();

                    b.ToTable("FoodServing", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.GeminiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int>("DailyRequestsUsed")
                        .HasColumnType("integer");

                    b.Property<string>("EncryptedApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalRequestsUsed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "KeyName" }, "UQ_GeminiKeys_KeyName")
                        .IsUnique();

                    b.ToTable("GeminiKeys", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.ImageDetection", b =>
                {
                    b.Property<int>("ImageDetectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImageDetectionId"));

                    b.Property<int>("AILogId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ImageDetectionId");

                    b.HasIndex("AILogId");

                    b.ToTable("ImageDetection", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.MealDiary", b =>
                {
                    b.Property<int>("MealDiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MealDiaryId"));

                    b.Property<decimal>("Calories")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Carb")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateOnly>("EatenDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Fat")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("FoodItemId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Grams")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MealTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("PortionQuantity")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Protein")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ServingUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceMethod")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int?>("UserDishId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserFoodItemId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("MealDiaryId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("ServingUnitId");

                    b.HasIndex("UserDishId");

                    b.HasIndex(new[] { "EatenDate" }, "IX_MealDiary_EatenDate")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex(new[] { "UserId", "EatenDate" }, "IX_MealDiary_UserDate")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("MealDiary", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.MealType", b =>
                {
                    b.Property<int>("MealTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MealTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MealTypeId");

                    b.HasIndex(new[] { "Name" }, "UQ_MealType_Name")
                        .IsUnique();

                    b.ToTable("MealType", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.NutritionTarget", b =>
                {
                    b.Property<int>("NutritionTargetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NutritionTargetId"));

                    b.Property<int?>("ActivityLevelId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<int>("TargetCalories")
                        .HasColumnType("integer")
                        .HasColumnName("CaloriesTarget");

                    b.Property<int>("TargetCarb")
                        .HasColumnType("integer")
                        .HasColumnName("CarbTarget");

                    b.Property<int>("TargetFat")
                        .HasColumnType("integer")
                        .HasColumnName("FatTarget");

                    b.Property<int>("TargetProtein")
                        .HasColumnType("integer")
                        .HasColumnName("ProteinTarget");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("NutritionTargetId");

                    b.HasIndex("ActivityLevelId");

                    b.HasIndex(new[] { "UserId", "EffectiveFrom", "EffectiveTo" }, "IX_NutritionTarget_User_EffectiveWindow");

                    b.ToTable("NutritionTarget", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipe", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeIngredientId"));

                    b.Property<int>("FoodItemId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Grams")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.HasKey("RecipeIngredientId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex(new[] { "RecipeId" }, "IX_RecipeIngredient_Recipe");

                    b.ToTable("RecipeIngredient", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.ServingUnit", b =>
                {
                    b.Property<int>("ServingUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServingUnitId"));

                    b.Property<bool>("IsBaseUnit")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ServingUnitId");

                    b.HasIndex(new[] { "Name" }, "UQ_ServingUnit_Name")
                        .IsUnique();

                    b.ToTable("ServingUnit", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("IsEmailVerified");

                    b.Property<DateTime?>("LastLogDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TargetWeightKg")
                        .HasColumnType("numeric");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("text")
                        .HasColumnName("EmailVerificationToken");

                    b.Property<DateTime?>("VerificationCodeExpiry")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("EmailVerificationExpiry");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EatFitAI.API.Models.UserDish", b =>
                {
                    b.Property<int>("UserDishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserDishId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserDishId");

                    b.HasIndex(new[] { "UserId", "DishName" }, "IX_UserDish_UserName")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("UserDish", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.UserDishIngredient", b =>
                {
                    b.Property<int>("UserDishIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserDishIngredientId"));

                    b.Property<int>("FoodItemId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Grams")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("UserDishId")
                        .HasColumnType("integer");

                    b.HasKey("UserDishIngredientId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("UserDishId");

                    b.ToTable("UserDishIngredient", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.UserFavoriteFood", b =>
                {
                    b.Property<int>("UserFavoriteFoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserFavoriteFoodId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserFavoriteFoodId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex(new[] { "UserId" }, "IX_UserFavoriteFood_User");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "IX_UserFavoriteFood_User_CreatedAt");

                    b.HasIndex(new[] { "UserId", "FoodItemId" }, "UQ_UserFavoriteFood")
                        .IsUnique();

                    b.ToTable("UserFavoriteFood", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.UserFoodItem", b =>
                {
                    b.Property<int>("UserFoodItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserFoodItemId"));

                    b.Property<decimal>("CaloriesPer100")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("CarbPer100")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<decimal>("FatPer100")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ProteinPer100")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserFoodItemId");

                    b.HasIndex(new[] { "UserId", "FoodName" }, "UQ_UserFoodItem_User_Name")
                        .IsUnique();

                    b.ToTable("UserFoodItem", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.UserPreference", b =>
                {
                    b.Property<int>("UserPreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserPreferenceId"));

                    b.Property<string>("Allergies")
                        .IsUnicode(true)
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("DietaryRestrictions")
                        .IsUnicode(true)
                        .HasColumnType("text");

                    b.Property<string>("PreferredCuisine")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PreferredMealsPerDay")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserPreferenceId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreference", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.UserRecentFood", b =>
                {
                    b.Property<int>("UserRecentFoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserRecentFoodId"));

                    b.Property<int>("FoodItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUsedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int>("UsedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserRecentFoodId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex(new[] { "UserId" }, "IX_UserRecentFood_User");

                    b.HasIndex(new[] { "UserId", "FoodItemId" }, "UQ_UserRecentFood")
                        .IsUnique();

                    b.ToTable("UserRecentFood", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.vw_DailyMacroShare", b =>
                {
                    b.Property<decimal?>("CarbShare")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<DateOnly>("EatenDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("FatShare")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<decimal?>("ProteinShare")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<decimal?>("TotalCalories")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalCarb")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalFat")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalProtein")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.ToTable((string)null);

                    b.ToView("vw_DailyMacroShare", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.vw_DailyNutritionTotal", b =>
                {
                    b.Property<DateOnly>("EatenDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("TotalCalories")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalCarb")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalFat")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalProtein")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.ToTable((string)null);

                    b.ToView("vw_DailyNutritionTotals", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.vw_MonthlyTotal", b =>
                {
                    b.Property<int?>("EntryCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("Month")
                        .HasColumnType("date");

                    b.Property<decimal?>("TotalCalories")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalCarb")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalFat")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalProtein")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.ToTable((string)null);

                    b.ToView("vw_MonthlyTotals", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.vw_TargetProgress", b =>
                {
                    b.Property<int?>("CalorieDelta")
                        .HasColumnType("integer");

                    b.Property<int?>("CarbDelta")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EatenDate")
                        .HasColumnType("date");

                    b.Property<int?>("FatDelta")
                        .HasColumnType("integer");

                    b.Property<int?>("ProteinDelta")
                        .HasColumnType("integer");

                    b.Property<int>("TargetCalories")
                        .HasColumnType("integer");

                    b.Property<int>("TargetCarb")
                        .HasColumnType("integer");

                    b.Property<int>("TargetFat")
                        .HasColumnType("integer");

                    b.Property<int>("TargetProtein")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalCalories")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalCarb")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalFat")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalProtein")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.ToTable((string)null);

                    b.ToView("vw_TargetProgress", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.vw_WeeklyNutritionTotal", b =>
                {
                    b.Property<decimal?>("TotalCalories")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalCarb")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalFat")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalProtein")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("WeekStart")
                        .HasColumnType("date");

                    b.ToTable((string)null);

                    b.ToView("vw_WeeklyNutritionTotals", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.Models.AILog", b =>
                {
                    b.HasOne("EatFitAI.API.Models.User", "User")
                        .WithMany("AILogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_AILog_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.API.Models.AISuggestion", b =>
                {
                    b.HasOne("EatFitAI.API.Models.AILog", "AILog")
                        .WithMany("AISuggestions")
                        .HasForeignKey("AILogId")
                        .IsRequired()
                        .HasConstraintName("FK_AISuggestion_AILog");

                    b.HasOne("EatFitAI.API.Models.FoodItem", "FoodItem")
                        .WithMany("AISuggestions")
                        .HasForeignKey("FoodItemId")
                        .IsRequired()
                        .HasConstraintName("FK_AISuggestion_FoodItem");

                    b.Navigation("AILog");

                    b.Navigation("FoodItem");
                });

            modelBuilder.Entity("EatFitAI.API.Models.AiCorrectionEvent", b =>
                {
                    b.HasOne("EatFitAI.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_AiCorrectionEvent_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.API.Models.BodyMetric", b =>
                {
                    b.HasOne("EatFitAI.API.Models.User", "User")
                        .WithMany("BodyMetrics")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_BodyMetric_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.API.Models.FoodServing", b =>
                {
                    b.HasOne("EatFitAI.API.Models.FoodItem", "FoodItem")
                        .WithMany("FoodServings")
                        .HasForeignKey("FoodItemId")
                        .IsRequired()
                        .HasConstraintName("FK_FoodServing_FoodItem");

                    b.HasOne("EatFitAI.API.Models.ServingUnit", "ServingUnit")
                        .WithMany("FoodServings")
                        .HasForeignKey("ServingUnitId")
                        .IsRequired()
                        .HasConstraintName("FK_FoodServing_ServingUnit");

                    b.Navigation("FoodItem");

                    b.Navigation("ServingUnit");
                });

            modelBuilder.Entity("EatFitAI.API.Models.ImageDetection", b =>
                {
                    b.HasOne("EatFitAI.API.Models.AILog", "AILog")
                        .WithMany("ImageDetections")
                        .HasForeignKey("AILogId")
                        .IsRequired()
                        .HasConstraintName("FK_ImageDetection_AILog");

                    b.Navigation("AILog");
                });

            modelBuilder.Entity("EatFitAI.API.Models.MealDiary", b =>
                {
                    b.HasOne("EatFitAI.API.Models.FoodItem", "FoodItem")
                        .WithMany("MealDiaries")
                        .HasForeignKey("FoodItemId")
                        .HasConstraintName("FK_MealDiary_FoodItem");

                    b.HasOne("EatFitAI.API.Models.MealType", "MealType")
                        .WithMany("MealDiaries")
                        .HasForeignKey("MealTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_MealDiary_MealType");

                    b.HasOne("EatFitAI.API.Models.Recipe", "Recipe")
                        .WithMany("MealDiaries")
                        .HasForeignKey("RecipeId")
                        .HasConstraintName("FK_MealDiary_Recipe");

                    b.HasOne("EatFitAI.API.Models.ServingUnit", "ServingUnit")
                        .WithMany("MealDiaries")
                        .HasForeignKey("ServingUnitId")
                        .HasConstraintName("FK_MealDiary_ServingUnit");

                    b.HasOne("EatFitAI.API.Models.UserDish", "UserDish")
                        .WithMany("MealDiaries")
                        .HasForeignKey("UserDishId")
                        .HasConstraintName("FK_MealDiary_UserDish");

                    b.HasOne("EatFitAI.API.Models.User", "User")
                        .WithMany("MealDiaries")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_MealDiary_User");

                    b.Navigation("FoodItem");

                    b.Navigation("MealType");

                    b.Navigation("Recipe");

                    b.Navigation("ServingUnit");

                    b.Navigation("User");

                    b.Navigation("UserDish");
                });

            modelBuilder.Entity("EatFitAI.API.Models.NutritionTarget", b =>
                {
                    b.HasOne("EatFitAI.API.Models.ActivityLevel", "ActivityLevel")
                        .WithMany("NutritionTargets")
                        .HasForeignKey("ActivityLevelId")
                        .HasConstraintName("FK_NutritionTarget_ActivityLevel");

                    b.HasOne("EatFitAI.API.Models.User", "User")
                        .WithMany("NutritionTargets")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_NutritionTarget_User");

                    b.Navigation("ActivityLevel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.API.Models.RecipeIngredient", b =>
                {
                    b.HasOne("EatFitAI.API.Models.FoodItem", "FoodItem")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("FoodItemId")
                        .IsRequired()
                        .HasConstraintName("FK_RecipeIngredient_FoodItem");

                    b.HasOne("EatFitAI.API.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .IsRequired()
                        .HasConstraintName("FK_RecipeIngredient_Recipe");

                    b.Navigation("FoodItem");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("EatFitAI.API.Models.UserDish", b =>
                {
                    b.HasOne("EatFitAI.API.Models.User", "User")
                        .WithMany("UserDishes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserDish_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.API.Models.UserDishIngredient", b =>
                {
                    b.HasOne("EatFitAI.API.Models.FoodItem", "FoodItem")
                        .WithMany("UserDishIngredients")
                        .HasForeignKey("FoodItemId")
                        .IsRequired()
                        .HasConstraintName("FK_UserDishIngredient_FoodItem");

                    b.HasOne("EatFitAI.API.Models.UserDish", "UserDish")
                        .WithMany("UserDishIngredients")
                        .HasForeignKey("UserDishId")
                        .IsRequired()
                        .HasConstraintName("FK_UserDishIngredient_UserDish");

                    b.Navigation("FoodItem");

                    b.Navigation("UserDish");
                });

            modelBuilder.Entity("EatFitAI.API.Models.UserFavoriteFood", b =>
                {
                    b.HasOne("EatFitAI.API.Models.FoodItem", "FoodItem")
                        .WithMany("UserFavoriteFoods")
                        .HasForeignKey("FoodItemId")
                        .IsRequired()
                        .HasConstraintName("FK_UserFavoriteFood_FoodItem");

                    b.HasOne("EatFitAI.API.Models.User", "User")
                        .WithMany("UserFavoriteFoods")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserFavoriteFood_User");

                    b.Navigation("FoodItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.API.Models.UserFoodItem", b =>
                {
                    b.HasOne("EatFitAI.API.Models.User", "User")
                        .WithMany("UserFoodItems")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserFoodItem_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.API.Models.UserPreference", b =>
                {
                    b.HasOne("EatFitAI.API.Models.User", "User")
                        .WithOne("UserPreference")
                        .HasForeignKey("EatFitAI.API.Models.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserPreference_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.API.Models.UserRecentFood", b =>
                {
                    b.HasOne("EatFitAI.API.Models.FoodItem", "FoodItem")
                        .WithMany("UserRecentFoods")
                        .HasForeignKey("FoodItemId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRecentFood_FoodItem");

                    b.HasOne("EatFitAI.API.Models.User", "User")
                        .WithMany("UserRecentFoods")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRecentFood_User");

                    b.Navigation("FoodItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.API.Models.AILog", b =>
                {
                    b.Navigation("AISuggestions");

                    b.Navigation("ImageDetections");
                });

            modelBuilder.Entity("EatFitAI.API.Models.ActivityLevel", b =>
                {
                    b.Navigation("NutritionTargets");
                });

            modelBuilder.Entity("EatFitAI.API.Models.FoodItem", b =>
                {
                    b.Navigation("AISuggestions");

                    b.Navigation("FoodServings");

                    b.Navigation("MealDiaries");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("UserDishIngredients");

                    b.Navigation("UserFavoriteFoods");

                    b.Navigation("UserRecentFoods");
                });

            modelBuilder.Entity("EatFitAI.API.Models.MealType", b =>
                {
                    b.Navigation("MealDiaries");
                });

            modelBuilder.Entity("EatFitAI.API.Models.Recipe", b =>
                {
                    b.Navigation("MealDiaries");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("EatFitAI.API.Models.ServingUnit", b =>
                {
                    b.Navigation("FoodServings");

                    b.Navigation("MealDiaries");
                });

            modelBuilder.Entity("EatFitAI.API.Models.User", b =>
                {
                    b.Navigation("AILogs");

                    b.Navigation("BodyMetrics");

                    b.Navigation("MealDiaries");

                    b.Navigation("NutritionTargets");

                    b.Navigation("UserDishes");

                    b.Navigation("UserFavoriteFoods");

                    b.Navigation("UserFoodItems");

                    b.Navigation("UserPreference");

                    b.Navigation("UserRecentFoods");
                });

            modelBuilder.Entity("EatFitAI.API.Models.UserDish", b =>
                {
                    b.Navigation("MealDiaries");

                    b.Navigation("UserDishIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
