using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EatFitAI.API.Migrations
{
    public partial class DailyNutritionLoopContracts : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                ALTER TABLE "MealDiary"
                    ADD COLUMN IF NOT EXISTS "InputMethod" character varying(30),
                    ADD COLUMN IF NOT EXISTS "IsRoughLog" boolean NOT NULL DEFAULT false,
                    ADD COLUMN IF NOT EXISTS "UserConfirmed" boolean NOT NULL DEFAULT true,
                    ADD COLUMN IF NOT EXISTS "ConfidenceScore" numeric(5,4),
                    ADD COLUMN IF NOT EXISTS "TrustSource" character varying(50),
                    ADD COLUMN IF NOT EXISTS "DiaryMissingNutrients" character varying(200);

                CREATE TABLE IF NOT EXISTS "MealDayMarker" (
                    "MealDayMarkerId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "UserId" uuid NOT NULL,
                    "LocalDate" date NOT NULL,
                    "MealTypeId" integer NULL,
                    "MarkerType" character varying(40) NOT NULL,
                    "Reason" character varying(200),
                    "CreatedAt" timestamp(3) with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
                    "UpdatedAt" timestamp(3) with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
                    "IsDeleted" boolean NOT NULL DEFAULT false
                );

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_MealDayMarker_User'
                    ) THEN
                        ALTER TABLE "MealDayMarker"
                            ADD CONSTRAINT "FK_MealDayMarker_User"
                            FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId");
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_MealDayMarker_MealType'
                    ) THEN
                        ALTER TABLE "MealDayMarker"
                            ADD CONSTRAINT "FK_MealDayMarker_MealType"
                            FOREIGN KEY ("MealTypeId") REFERENCES "MealType" ("MealTypeId");
                    END IF;
                END $$;

                CREATE INDEX IF NOT EXISTS "IX_MealDayMarker_UserDate"
                    ON "MealDayMarker" ("UserId", "LocalDate")
                    WHERE "IsDeleted" = false;

                CREATE INDEX IF NOT EXISTS "IX_MealDayMarker_UserDateMealType"
                    ON "MealDayMarker" ("UserId", "LocalDate", "MealTypeId", "MarkerType")
                    WHERE "IsDeleted" = false;

                CREATE TABLE IF NOT EXISTS "WeeklyReviewAction" (
                    "WeeklyReviewActionId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "UserId" uuid NOT NULL,
                    "WeekStartDate" date NOT NULL,
                    "ActionKey" character varying(80) NOT NULL,
                    "Label" character varying(200) NOT NULL,
                    "Status" character varying(30) NOT NULL DEFAULT 'suggested',
                    "ReplacementText" character varying(200),
                    "CreatedAt" timestamp(3) with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
                    "UpdatedAt" timestamp(3) with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
                );

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_WeeklyReviewAction_User'
                    ) THEN
                        ALTER TABLE "WeeklyReviewAction"
                            ADD CONSTRAINT "FK_WeeklyReviewAction_User"
                            FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId");
                    END IF;
                END $$;

                CREATE UNIQUE INDEX IF NOT EXISTS "UQ_WeeklyReviewAction_UserWeekAction"
                    ON "WeeklyReviewAction" ("UserId", "WeekStartDate", "ActionKey");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS "WeeklyReviewAction";

                DROP TABLE IF EXISTS "MealDayMarker";

                ALTER TABLE "MealDiary"
                    DROP COLUMN IF EXISTS "InputMethod",
                    DROP COLUMN IF EXISTS "IsRoughLog",
                    DROP COLUMN IF EXISTS "UserConfirmed",
                    DROP COLUMN IF EXISTS "ConfidenceScore",
                    DROP COLUMN IF EXISTS "TrustSource",
                    DROP COLUMN IF EXISTS "DiaryMissingNutrients";
                """);
        }
    }
}
