// <auto-generated />
using System;
using EatFitAI.API.DbScaffold.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EatFitAI.API.Migrations.EatFitAIDb
{
    [DbContext(typeof(EatFitAIDbContext))]
    [Migration("20251219000130_AddStreakAndTargetWeight")]
    partial class AddStreakAndTargetWeight
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.AILog", b =>
                {
                    b.Property<int>("AILogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AILogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("InputJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AILogId");

                    b.HasIndex("UserId");

                    b.ToTable("AILog", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.AISuggestion", b =>
                {
                    b.Property<int>("AISuggestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AISuggestionId"));

                    b.Property<int>("AILogId")
                        .HasColumnType("int");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int");

                    b.HasKey("AISuggestionId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex(new[] { "AILogId" }, "IX_AISuggestion_AILog");

                    b.ToTable("AISuggestion", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.ActivityLevel", b =>
                {
                    b.Property<int>("ActivityLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityLevelId"));

                    b.Property<decimal>("ActivityFactor")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ActivityLevelId");

                    b.HasIndex(new[] { "Name" }, "UQ_ActivityLevel_Name")
                        .IsUnique();

                    b.ToTable("ActivityLevel", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.BodyMetric", b =>
                {
                    b.Property<int>("BodyMetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BodyMetricId"));

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateOnly>("MeasuredDate")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("BodyMetricId");

                    b.HasIndex("UserId");

                    b.ToTable("BodyMetric", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.FoodItem", b =>
                {
                    b.Property<int>("FoodItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodItemId"));

                    b.Property<decimal>("CaloriesPer100g")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("CarbPer100g")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<decimal>("FatPer100g")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("ProteinPer100g")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ThumbNail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("FoodItemId");

                    b.HasIndex(new[] { "FoodName" }, "IX_FoodItem_Name")
                        .HasFilter("([IsDeleted]=(0))");

                    b.ToTable("FoodItem", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.FoodServing", b =>
                {
                    b.Property<int>("FoodServingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodServingId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("GramsPerUnit")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ServingUnitId")
                        .HasColumnType("int");

                    b.HasKey("FoodServingId");

                    b.HasIndex("ServingUnitId");

                    b.HasIndex(new[] { "FoodItemId", "ServingUnitId" }, "UQ_FoodServing")
                        .IsUnique();

                    b.ToTable("FoodServing", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.ImageDetection", b =>
                {
                    b.Property<int>("ImageDetectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageDetectionId"));

                    b.Property<int>("AILogId")
                        .HasColumnType("int");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ImageDetectionId");

                    b.HasIndex("AILogId");

                    b.ToTable("ImageDetection", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.MealDiary", b =>
                {
                    b.Property<int>("MealDiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealDiaryId"));

                    b.Property<decimal>("Calories")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Carb")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateOnly>("EatenDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Fat")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Grams")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MealTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("PortionQuantity")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Protein")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int?>("ServingUnitId")
                        .HasColumnType("int");

                    b.Property<string>("SourceMethod")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("UserDishId")
                        .HasColumnType("int");

                    b.Property<int?>("UserFoodItemId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MealDiaryId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("ServingUnitId");

                    b.HasIndex("UserDishId");

                    b.HasIndex(new[] { "EatenDate" }, "IX_MealDiary_EatenDate")
                        .HasFilter("([IsDeleted]=(0))");

                    b.HasIndex(new[] { "UserId", "EatenDate" }, "IX_MealDiary_UserDate")
                        .HasFilter("([IsDeleted]=(0))");

                    b.ToTable("MealDiary", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.MealType", b =>
                {
                    b.Property<int>("MealTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MealTypeId");

                    b.HasIndex(new[] { "Name" }, "UQ_MealType_Name")
                        .IsUnique();

                    b.ToTable("MealType", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.NutritionTarget", b =>
                {
                    b.Property<int>("NutritionTargetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NutritionTargetId"));

                    b.Property<int?>("ActivityLevelId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("Goal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetCalories")
                        .HasColumnType("int");

                    b.Property<int>("TargetCarb")
                        .HasColumnType("int");

                    b.Property<int>("TargetFat")
                        .HasColumnType("int");

                    b.Property<int>("TargetProtein")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NutritionTargetId");

                    b.HasIndex("ActivityLevelId");

                    b.HasIndex("UserId");

                    b.ToTable("NutritionTarget", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipe", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeIngredientId"));

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Grams")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("RecipeIngredientId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex(new[] { "RecipeId" }, "IX_RecipeIngredient_Recipe");

                    b.ToTable("RecipeIngredient", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.ServingUnit", b =>
                {
                    b.Property<int>("ServingUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServingUnitId"));

                    b.Property<bool>("IsBaseUnit")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ServingUnitId");

                    b.HasIndex(new[] { "Name" }, "UQ_ServingUnit_Name")
                        .IsUnique();

                    b.ToTable("ServingUnit", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int?>("ActivityLevelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLogDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("int");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TargetWeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerificationCodeExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("ActivityLevelId");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.UserDish", b =>
                {
                    b.Property<int>("UserDishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserDishId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserDishId");

                    b.HasIndex(new[] { "UserId", "DishName" }, "IX_UserDish_UserName")
                        .HasFilter("([IsDeleted]=(0))");

                    b.ToTable("UserDish", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.UserDishIngredient", b =>
                {
                    b.Property<int>("UserDishIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserDishIngredientId"));

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Grams")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("UserDishId")
                        .HasColumnType("int");

                    b.HasKey("UserDishIngredientId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("UserDishId");

                    b.ToTable("UserDishIngredient", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.UserFavoriteFood", b =>
                {
                    b.Property<int>("UserFavoriteFoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserFavoriteFoodId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserFavoriteFoodId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex(new[] { "UserId" }, "IX_UserFavoriteFood_User");

                    b.HasIndex(new[] { "UserId", "FoodItemId" }, "UQ_UserFavoriteFood")
                        .IsUnique();

                    b.ToTable("UserFavoriteFood", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.UserFoodItem", b =>
                {
                    b.Property<int>("UserFoodItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserFoodItemId"));

                    b.Property<decimal>("CaloriesPer100")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("CarbPer100")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<decimal>("FatPer100")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("ProteinPer100")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserFoodItemId");

                    b.HasIndex(new[] { "UserId", "FoodName" }, "UQ_UserFoodItem_User_Name")
                        .IsUnique();

                    b.ToTable("UserFoodItem", null, t =>
                        {
                            t.HasTrigger("tr_UserFoodItem_SetUpdatedAt");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.UserRecentFood", b =>
                {
                    b.Property<int>("UserRecentFoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRecentFoodId"));

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUsedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("UsedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserRecentFoodId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex(new[] { "UserId" }, "IX_UserRecentFood_User");

                    b.HasIndex(new[] { "UserId", "FoodItemId" }, "UQ_UserRecentFood")
                        .IsUnique();

                    b.ToTable("UserRecentFood", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.vw_AiFoodMap", b =>
                {
                    b.Property<decimal?>("CaloriesPer100g")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("CarbPer100g")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("FatPer100g")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<string>("FoodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("MinConfidence")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("ProteinPer100g")
                        .HasColumnType("decimal(10, 2)");

                    b.ToTable((string)null);

                    b.ToView("vw_AiFoodMap", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.vw_DailyMacroShare", b =>
                {
                    b.Property<decimal?>("CarbShare")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<DateOnly>("EatenDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("FatShare")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<decimal?>("ProteinShare")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<decimal?>("TotalCalories")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalCarb")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalFat")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalProtein")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable((string)null);

                    b.ToView("vw_DailyMacroShare", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.vw_DailyNutritionTotal", b =>
                {
                    b.Property<DateOnly>("EatenDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("TotalCalories")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalCarb")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalFat")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalProtein")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable((string)null);

                    b.ToView("vw_DailyNutritionTotals", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.vw_MonthlyTotal", b =>
                {
                    b.Property<int?>("EntryCount")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Month")
                        .HasColumnType("date");

                    b.Property<decimal?>("TotalCalories")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalCarb")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalFat")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalProtein")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable((string)null);

                    b.ToView("vw_MonthlyTotals", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.vw_TargetProgress", b =>
                {
                    b.Property<int?>("CalorieDelta")
                        .HasColumnType("int");

                    b.Property<int?>("CarbDelta")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EatenDate")
                        .HasColumnType("date");

                    b.Property<int?>("FatDelta")
                        .HasColumnType("int");

                    b.Property<int?>("ProteinDelta")
                        .HasColumnType("int");

                    b.Property<int>("TargetCalories")
                        .HasColumnType("int");

                    b.Property<int>("TargetCarb")
                        .HasColumnType("int");

                    b.Property<int>("TargetFat")
                        .HasColumnType("int");

                    b.Property<int>("TargetProtein")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalCalories")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalCarb")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalFat")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalProtein")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable((string)null);

                    b.ToView("vw_TargetProgress", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.vw_WeeklyNutritionTotal", b =>
                {
                    b.Property<decimal?>("TotalCalories")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalCarb")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalFat")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalProtein")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("WeekStart")
                        .HasColumnType("date");

                    b.ToTable((string)null);

                    b.ToView("vw_WeeklyNutritionTotals", (string)null);
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.AILog", b =>
                {
                    b.HasOne("EatFitAI.API.DbScaffold.Models.User", "User")
                        .WithMany("AILogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_AILog_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.AISuggestion", b =>
                {
                    b.HasOne("EatFitAI.API.DbScaffold.Models.AILog", "AILog")
                        .WithMany("AISuggestions")
                        .HasForeignKey("AILogId")
                        .IsRequired()
                        .HasConstraintName("FK_AISuggestion_AILog");

                    b.HasOne("EatFitAI.API.DbScaffold.Models.FoodItem", "FoodItem")
                        .WithMany("AISuggestions")
                        .HasForeignKey("FoodItemId")
                        .IsRequired()
                        .HasConstraintName("FK_AISuggestion_FoodItem");

                    b.Navigation("AILog");

                    b.Navigation("FoodItem");
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.BodyMetric", b =>
                {
                    b.HasOne("EatFitAI.API.DbScaffold.Models.User", "User")
                        .WithMany("BodyMetrics")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_BodyMetric_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.FoodServing", b =>
                {
                    b.HasOne("EatFitAI.API.DbScaffold.Models.FoodItem", "FoodItem")
                        .WithMany("FoodServings")
                        .HasForeignKey("FoodItemId")
                        .IsRequired()
                        .HasConstraintName("FK_FoodServing_FoodItem");

                    b.HasOne("EatFitAI.API.DbScaffold.Models.ServingUnit", "ServingUnit")
                        .WithMany("FoodServings")
                        .HasForeignKey("ServingUnitId")
                        .IsRequired()
                        .HasConstraintName("FK_FoodServing_ServingUnit");

                    b.Navigation("FoodItem");

                    b.Navigation("ServingUnit");
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.ImageDetection", b =>
                {
                    b.HasOne("EatFitAI.API.DbScaffold.Models.AILog", "AILog")
                        .WithMany("ImageDetections")
                        .HasForeignKey("AILogId")
                        .IsRequired()
                        .HasConstraintName("FK_ImageDetection_AILog");

                    b.Navigation("AILog");
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.MealDiary", b =>
                {
                    b.HasOne("EatFitAI.API.DbScaffold.Models.FoodItem", "FoodItem")
                        .WithMany("MealDiaries")
                        .HasForeignKey("FoodItemId")
                        .HasConstraintName("FK_MealDiary_FoodItem");

                    b.HasOne("EatFitAI.API.DbScaffold.Models.MealType", "MealType")
                        .WithMany("MealDiaries")
                        .HasForeignKey("MealTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_MealDiary_MealType");

                    b.HasOne("EatFitAI.API.DbScaffold.Models.Recipe", "Recipe")
                        .WithMany("MealDiaries")
                        .HasForeignKey("RecipeId")
                        .HasConstraintName("FK_MealDiary_Recipe");

                    b.HasOne("EatFitAI.API.DbScaffold.Models.ServingUnit", "ServingUnit")
                        .WithMany("MealDiaries")
                        .HasForeignKey("ServingUnitId")
                        .HasConstraintName("FK_MealDiary_ServingUnit");

                    b.HasOne("EatFitAI.API.DbScaffold.Models.UserDish", "UserDish")
                        .WithMany("MealDiaries")
                        .HasForeignKey("UserDishId")
                        .HasConstraintName("FK_MealDiary_UserDish");

                    b.HasOne("EatFitAI.API.DbScaffold.Models.User", "User")
                        .WithMany("MealDiaries")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_MealDiary_User");

                    b.Navigation("FoodItem");

                    b.Navigation("MealType");

                    b.Navigation("Recipe");

                    b.Navigation("ServingUnit");

                    b.Navigation("User");

                    b.Navigation("UserDish");
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.NutritionTarget", b =>
                {
                    b.HasOne("EatFitAI.API.DbScaffold.Models.ActivityLevel", "ActivityLevel")
                        .WithMany("NutritionTargets")
                        .HasForeignKey("ActivityLevelId")
                        .HasConstraintName("FK_NutritionTarget_ActivityLevel");

                    b.HasOne("EatFitAI.API.DbScaffold.Models.User", "User")
                        .WithMany("NutritionTargets")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_NutritionTarget_User");

                    b.Navigation("ActivityLevel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.RecipeIngredient", b =>
                {
                    b.HasOne("EatFitAI.API.DbScaffold.Models.FoodItem", "FoodItem")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("FoodItemId")
                        .IsRequired()
                        .HasConstraintName("FK_RecipeIngredient_FoodItem");

                    b.HasOne("EatFitAI.API.DbScaffold.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .IsRequired()
                        .HasConstraintName("FK_RecipeIngredient_Recipe");

                    b.Navigation("FoodItem");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.User", b =>
                {
                    b.HasOne("EatFitAI.API.DbScaffold.Models.ActivityLevel", "ActivityLevel")
                        .WithMany()
                        .HasForeignKey("ActivityLevelId");

                    b.Navigation("ActivityLevel");
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.UserDish", b =>
                {
                    b.HasOne("EatFitAI.API.DbScaffold.Models.User", "User")
                        .WithMany("UserDishes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserDish_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.UserDishIngredient", b =>
                {
                    b.HasOne("EatFitAI.API.DbScaffold.Models.FoodItem", "FoodItem")
                        .WithMany("UserDishIngredients")
                        .HasForeignKey("FoodItemId")
                        .IsRequired()
                        .HasConstraintName("FK_UserDishIngredient_FoodItem");

                    b.HasOne("EatFitAI.API.DbScaffold.Models.UserDish", "UserDish")
                        .WithMany("UserDishIngredients")
                        .HasForeignKey("UserDishId")
                        .IsRequired()
                        .HasConstraintName("FK_UserDishIngredient_UserDish");

                    b.Navigation("FoodItem");

                    b.Navigation("UserDish");
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.UserFavoriteFood", b =>
                {
                    b.HasOne("EatFitAI.API.DbScaffold.Models.FoodItem", "FoodItem")
                        .WithMany("UserFavoriteFoods")
                        .HasForeignKey("FoodItemId")
                        .IsRequired()
                        .HasConstraintName("FK_UserFavoriteFood_FoodItem");

                    b.HasOne("EatFitAI.API.DbScaffold.Models.User", "User")
                        .WithMany("UserFavoriteFoods")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserFavoriteFood_User");

                    b.Navigation("FoodItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.UserFoodItem", b =>
                {
                    b.HasOne("EatFitAI.API.DbScaffold.Models.User", "User")
                        .WithMany("UserFoodItems")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserFoodItem_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.UserRecentFood", b =>
                {
                    b.HasOne("EatFitAI.API.DbScaffold.Models.FoodItem", "FoodItem")
                        .WithMany("UserRecentFoods")
                        .HasForeignKey("FoodItemId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRecentFood_FoodItem");

                    b.HasOne("EatFitAI.API.DbScaffold.Models.User", "User")
                        .WithMany("UserRecentFoods")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRecentFood_User");

                    b.Navigation("FoodItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.AILog", b =>
                {
                    b.Navigation("AISuggestions");

                    b.Navigation("ImageDetections");
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.ActivityLevel", b =>
                {
                    b.Navigation("NutritionTargets");
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.FoodItem", b =>
                {
                    b.Navigation("AISuggestions");

                    b.Navigation("FoodServings");

                    b.Navigation("MealDiaries");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("UserDishIngredients");

                    b.Navigation("UserFavoriteFoods");

                    b.Navigation("UserRecentFoods");
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.MealType", b =>
                {
                    b.Navigation("MealDiaries");
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.Recipe", b =>
                {
                    b.Navigation("MealDiaries");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.ServingUnit", b =>
                {
                    b.Navigation("FoodServings");

                    b.Navigation("MealDiaries");
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.User", b =>
                {
                    b.Navigation("AILogs");

                    b.Navigation("BodyMetrics");

                    b.Navigation("MealDiaries");

                    b.Navigation("NutritionTargets");

                    b.Navigation("UserDishes");

                    b.Navigation("UserFavoriteFoods");

                    b.Navigation("UserFoodItems");

                    b.Navigation("UserRecentFoods");
                });

            modelBuilder.Entity("EatFitAI.API.DbScaffold.Models.UserDish", b =>
                {
                    b.Navigation("MealDiaries");

                    b.Navigation("UserDishIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
