export const TEST_IDS = {
  auth: {
    welcomeScreen: 'auth-welcome-screen',
    welcomeLoginButton: 'auth-welcome-login-button',
    welcomeRegisterButton: 'auth-welcome-register-button',
    loginScreen: 'auth-login-screen',
    emailInput: 'auth-login-email-input',
    passwordInput: 'auth-login-password-input',
    submitButton: 'auth-login-submit-button',
  },
  home: {
    screen: 'home-screen',
    searchButton: 'home-search-food-button',
    quickAddSearchButton: 'home-quick-add-search-button',
    quickAddScanButton: 'home-quick-add-scan-button',
    quickAddVoiceButton: 'home-quick-add-voice-button',
    diaryButton: 'home-view-diary-button',
    fabButton: 'home-smart-add-fab',
  },
  foodSearch: {
    screen: 'food-search-screen',
    queryInput: 'food-search-query-input',
    submitButton: 'food-search-submit-button',
    firstResultCard: 'food-search-first-result-card',
    firstAddButton: 'food-search-add-first-item-button',
  },
  mealDiary: {
    screen: 'meal-diary-screen',
    datePickerButton: 'meal-diary-date-picker-button',
    dateChipPrefix: 'meal-diary-date-chip',
    addManualButton: 'meal-diary-add-manual-button',
    emptyAddManualButton: 'meal-diary-empty-add-manual-button',
    backToTodayButton: 'meal-diary-back-to-today-button',
  },
  foodDetail: {
    screen: 'food-detail-screen',
    gramsInput: 'food-detail-grams-input',
    noteInput: 'food-detail-note-input',
    submitButton: 'food-detail-submit-button',
  },
  aiScan: {
    screen: 'ai-scan-screen',
    captureButton: 'ai-scan-capture-button',
    galleryButton: 'ai-scan-gallery-button',
    retakeButton: 'ai-scan-retake-button',
    addToDiaryButton: 'ai-scan-add-to-diary-button',
    quickAddButton: 'ai-scan-quick-save-button',
    quickAddTopResultButton: 'ai-scan-quick-add-top-result-button',
  },
  visionAddMeal: {
    screen: 'vision-add-meal-screen',
    confirmButton: 'vision-add-meal-confirm-button',
    decreaseGramsButton: 'vision-add-meal-decrease-grams-button',
    increaseGramsButton: 'vision-add-meal-increase-grams-button',
    replaceButton: 'vision-add-meal-replace-button',
    mealTypeBreakfastButton: 'vision-add-meal-mealtype-breakfast-button',
    mealTypeLunchButton: 'vision-add-meal-mealtype-lunch-button',
    mealTypeDinnerButton: 'vision-add-meal-mealtype-dinner-button',
    mealTypeSnackButton: 'vision-add-meal-mealtype-snack-button',
  },
  foodPicker: {
    searchInput: 'food-picker-search-input',
    firstResult: 'food-picker-first-result',
  },
  error: {
    retryButton: 'app-error-retry-button',
  },
} as const;

